/* Aba "Materiais" do projeto: links, depoimentos e arquivos que o cliente enviou pelo formulário (ou que você cadastra aqui). */
const inUI = {edit: ''};
const IN_LINK_LAB = {site: 'Site', instagram: 'Instagram', redes: 'Outras redes', logo: 'Logo (link)', fotos: 'Fotos (link)', videos: 'Vídeos (link)', marca: 'Manual de marca / cores / fontes', jafeito: 'Materiais de comunicação já feitos'};
const IN_AUTH = {sim: 'Autorizado', pedir: 'Falta autorização', nao: 'Não pode usar'}, IN_CAT = {logo: 'Logo', fotos: 'Fotos da empresa', produtos: 'Fotos de produtos', materiais: 'Materiais já feitos', depoimentos: 'Depoimentos (prints)'};
const inP = () => { const p = curProject(); p.intake = normalizeIntake(p.intake); return p.intake; };
const inUrl = v => { v = String(v || '').trim(); const m = v.match(/^https?:\/\/\S+$/i); return m ? m[0] : (/^@[\w.]{2,40}$/.test(v) ? 'https://instagram.com/' + v.slice(1) : ''); };
function intakeHTML(p) {
  const it = inP(), links = IN_LINKS.map(k => `<div class="field ${k === 'jafeito' || k === 'marca' ? 'full' : ''}"><label>${esc(IN_LINK_LAB[k])}</label>${k === 'jafeito' || k === 'marca' ? `<textarea rows="2" oninput="inSetLink('${k}',this.value)">${esc(it.links[k])}</textarea>` : `<input value="${esc(it.links[k])}" oninput="inSetLink('${k}',this.value)" placeholder="https://… ou @perfil">`}${inUrl(it.links[k]) ? `<small><a href="${esc(inUrl(it.links[k]))}" target="_blank" rel="noopener">abrir ↗</a></small>` : ''}</div>`).join('');
  const dep = it.testimonials.map(t => inUI.edit === t.id ? inDepForm(t) : `<div class="list-item"><div><strong>${esc(t.who) || 'Sem nome'}</strong><small>${esc(IN_AUTH[t.auth])}${t.product ? ' · ' + esc(t.product) : ''}</small><p style="margin:6px 0 0;font-size:13.5px">${esc(t.text).slice(0, 280) || '<span class="muted">Sem texto (só link).</span>'}${t.link && inUrl(t.link) ? ` <a href="${esc(t.link)}" target="_blank" rel="noopener">ver ↗</a>` : ''}</p></div><div class="row-gap"><button class="btn sm" onclick="inEdit('${t.id}')">Editar</button><button class="btn sm" onclick="inDepDel('${t.id}')">Excluir</button></div></div>`).join('');
  const fl = it.files.length ? Object.entries(IN_CAT).map(([c, l]) => { const g = it.files.filter(f => f.cat === c); return g.length ? `<div style="margin-top:8px"><b style="font-size:13px">${l}</b> <small class="muted">${g.length}</small><div class="id-tags" style="margin-top:4px">${g.map(f => `<span class="id-tag">${esc(f.name)}${f.ext === 'pdf' && f.t ? ` <a href="api/briefing.php?t=${f.t}&f=${f.id}.pdf" target="_blank" rel="noopener">abrir</a>` : f.lib ? ' · na Biblioteca' : ''}</span>`).join('')}</div></div>` : ''; }).join('') : '<p class="muted">Nenhum arquivo recebido ainda. As imagens que o cliente enviar pelo briefing vão para a Biblioteca quando você importar as respostas.</p>';
  return `<div class="panel"><div class="section-row"><div><h3>Materiais do cliente</h3><p class="muted" style="margin:2px 0 0;font-size:12.5px">Links, depoimentos e arquivos. Chegam pelo <b>formulário do cliente</b> (Pré-Projeto → Briefing do cliente → Importar respostas) ou você preenche aqui.</p></div><button class="btn sm" onclick="ui.tab='preproject';renderProjectTab()">Abrir o formulário do cliente</button></div>
  <h4 style="margin:16px 0 8px">Links</h4><div class="form-grid">${links}</div></div>
  <div class="panel" style="margin-top:14px"><div class="section-row"><div><h3>Depoimentos de clientes</h3><p class="muted" style="margin:2px 0 0;font-size:12.5px">A IA só usa os marcados como <b>autorizados</b>.</p></div><button class="btn sm dark" onclick="inDepNew()">＋ Novo depoimento</button></div><div class="list">${dep || '<p class="muted">Nenhum depoimento ainda.</p>'}</div></div>
  <div class="panel" style="margin-top:14px"><h3>Arquivos recebidos</h3>${fl}${it.files.some(f => f.lib) ? `<div style="margin-top:10px"><button class="btn sm" onclick="go('biblioteca')">Abrir a Biblioteca de imagens</button></div>` : ''}</div>`;
}
let inT; function inSetLink(k, v) { inP().links[k] = String(v).slice(0, 1200); clearTimeout(inT); inT = setTimeout(persist, 400); }
function inDepForm(t) {
  return `<div class="list-item" style="display:block"><div class="form-grid"><div class="field"><label>Quem falou</label><input id="dpWho" value="${esc(t.who)}"></div><div class="field"><label>Sobre qual produto</label><input id="dpProd" value="${esc(t.product)}"></div><div class="field full"><label>O que disse</label><textarea id="dpText" rows="3">${esc(t.text)}</textarea></div><div class="field"><label>Link (vídeo, post, avaliação)</label><input id="dpLink" value="${esc(t.link)}"></div><div class="field"><label>Autorização</label><select id="dpAuth">${Object.entries(IN_AUTH).map(([k, l]) => `<option value="${k}" ${t.auth === k ? 'selected' : ''}>${l}</option>`).join('')}</select></div></div><div class="actions" style="margin-top:8px"><button class="btn sm dark" onclick="inDepSave('${t.id}')">Salvar</button><button class="btn sm" onclick="inUI.edit='';renderProjectTab()">Cancelar</button></div></div>`;
}
function inEdit(id) { inUI.edit = id; keepScroll(renderProjectTab); }
function inDepNew() { const it = inP(), t = {id: uid('dp'), who: '', text: '', link: '', product: '', auth: 'pedir'}; it.testimonials.unshift(t); inUI.edit = t.id; keepScroll(renderProjectTab); }
function inDepSave(id) { const it = inP(), t = it.testimonials.find(x => x.id === id); if (!t) return; Object.assign(t, {who: $('dpWho').value, product: $('dpProd').value, text: $('dpText').value, link: $('dpLink').value.trim(), auth: $('dpAuth').value}); if (!t.who.trim() && !t.text.trim()) it.testimonials = it.testimonials.filter(x => x.id !== id); curProject().intake = normalizeIntake(it); inUI.edit = ''; persist(); keepScroll(renderProjectTab); }
function inDepDel(id) { if (!confirm('Excluir este depoimento?')) return; const it = inP(); it.testimonials = it.testimonials.filter(x => x.id !== id); persist(); keepScroll(renderProjectTab); }
/* texto para a IA: só depoimentos autorizados e links */
function intakeTxt(p) {
  const it = p && p.intake; if (!it) return ''; const L = [];
  const lk = IN_LINKS.filter(k => (it.links[k] || '').trim()).map(k => `${IN_LINK_LAB[k]}: ${it.links[k].trim().slice(0, 200)}`); if (lk.length) L.push('Links da marca: ' + lk.join(' | '));
  const dp = it.testimonials.filter(t => t.auth === 'sim' && t.text.trim()); if (dp.length) L.push('Depoimentos AUTORIZADOS (use só estes, sem alterar o sentido):\n' + dp.slice(0, 8).map(t => `- "${t.text.slice(0, 300)}" (${t.who}${t.product ? ', sobre ' + t.product : ''})`).join('\n'));
  if (it.testimonials.some(t => t.auth !== 'sim')) L.push('Há depoimentos SEM autorização: não os use.');
  return L.length ? 'MATERIAIS DO CLIENTE\n' + L.join('\n') : '';
}
TABS.intake = intakeHTML;
