const journeyDiagnostics = [
  ["d1","Dependem de indicação para vender","Aquisição pouco previsível."],
  ["d2","Não têm previsão de fechamento","Baixa previsibilidade comercial."],
  ["d3","Não possuem área comercial especializada","Venda concentrada nos donos ou sem processo."],
  ["d4","Não possuem área de marketing especializada","Marketing pontual e pouco estruturado."],
  ["d5","Pensam marketing como custo","Dificuldade em tratar aquisição como parte do crescimento."],
  ["d6","Donos se dividem entre operação e gestão","O crescimento compete com a operação diária."],
  ["d7","Não focam em um produto específico","Posicionamento e comunicação ficam dispersos."],
  ["d8","Não possuem sistema de gestão de vendas","Oportunidades e follow-ups ficam sem acompanhamento."]
];
const journeyDiagState = {selected:{}, other:[]};

function buildDiagnosis(){
  const selected=journeyDiagnostics.filter(x=>journeyDiagState.selected[x[0]]);
  const texts=selected.map(x=>x[2]);
  const has=(id)=>!!journeyDiagState.selected[id];
  const hypotheses=[];
  selected.forEach((x,i)=>{
    const map={
      indicacao:'A dependência de indicação pode limitar a previsibilidade da geração de novas oportunidades.',
      fechamento:'A ausência de previsão de fechamento pode dificultar planejamento comercial e financeiro.',
      comercial:'A ausência de uma área comercial especializada pode deixar a conversão dependente da rotina dos próprios gestores.',
      marketing:'A ausência de marketing especializado pode reduzir consistência na geração e gestão da demanda.',
      custo:'Perceber marketing como custo pode dificultar sua integração aos objetivos de crescimento e aquisição.',
      operacao:'A divisão dos donos entre operação e gestão pode reduzir a capacidade de dedicar atenção contínua a crescimento e vendas.',
      produto:'A falta de foco em um produto específico pode dispersar posicionamento, comunicação, oferta e aquisição.',
      gestao:'A ausência de um sistema de gestão de vendas pode impedir acompanhamento consistente de oportunidades, conversão e origem dos negócios.'
    };
    hypotheses.push({title:`Hipótese ${String(i+1).padStart(2,'0')} · ${x[1]}`,text:map[x[0]]||`O desafio “${x[1]}” pode estar contribuindo para limitar a previsibilidade do crescimento e precisa ser validado.`});
  });
  if(!hypotheses.length) hypotheses.push({title:'Hipótese inicial',text:'Selecione os desafios do negócio para que o Studio construa hipóteses específicas.'});
  const diagnosis = selected.length ? 'O conjunto de desafios sugere possíveis gargalos na geração de demanda, na conversão comercial e/ou na gestão do crescimento. O diagnóstico consolidado deve ser validado com o cliente antes de virar decisão.' : 'Ainda não há dados suficientes para consolidar um diagnóstico.';
  const justification = selected.length ? 'A justificativa para intervenção é criar tração comercial sem esperar a estrutura perfeita: primeiro colocamos demanda qualificada para dentro e, em paralelo, construímos o fluxo mínimo necessário para receber, qualificar e acompanhar esses leads.' : 'A justificativa será construída a partir dos desafios validados.';
  const objective = selected.length ? 'Aumentar a previsibilidade do crescimento por meio da geração contínua de oportunidades e da estruturação progressiva do processo de conversão.' : 'Definir um objetivo após validar o diagnóstico.';
  return {selected,hypotheses,diagnosis,justification,objective,hasTraction:selected.length>0,has};
}
function renderJourneyArchitect(){
  const c=$('projectContent'); if(!c)return;
  const d=buildDiagnosis();
  const selectedCount=d.selected.length+journeyDiagState.other.length;
  const chips=journeyDiagnostics.filter(x=>journeyDiagState.selected[x[0]]).map(x=>`<span class="jp-tag">${x[1]} <b>✓</b></span>`).join('')+journeyDiagState.other.map(x=>`<span class="jp-tag">${x} <b>✓</b></span>`).join('');
  const okrTraction=[
    'Definir uma meta inicial de leads qualificados por período.',
    'Colocar pelo menos um canal de aquisição em operação.',
    'Medir volume, qualidade e origem dos leads gerados.'
  ];
  const okrStructure=[
    'Registrar 100% dos leads recebidos em um fluxo mínimo de acompanhamento.',
    'Definir critérios de qualificação e responsáveis pelo atendimento.',
    'Acompanhar conversão por etapa do processo comercial.'
  ];
  c.innerHTML=`
  <div class="jp-wrap">
    <div class="jp-head"><div><div class="eyebrow">JOURNEY ARCHITECT · MOTOR DO PROJETO</div><h2>Diagnóstico & Pré-Projeto</h2><p>Transforme desafios em hipóteses, diagnóstico, justificativa e objetivo mensurável. O pré-projeto define onde começar sem antecipar decisões que dependem do posicionamento.</p></div>
      <div class="jp-actions"><span class="jp-status" id="jpStatus">RASCUNHO</span><button class="btn" onclick="jpEditBrief()">✎ Editar briefing</button><button class="btn" onclick="jpPresent()">▣ Apresentação</button><button class="btn" onclick="jpPDF()">PDF</button><button class="btn dark" onclick="jpApprove()">✓ Aprovar pré-projeto</button></div></div>
    <div class="jp-progress"><span class="jp-step active">01 Diagnóstico</span><span class="jp-step">02 Hipóteses</span><span class="jp-step">03 Justificativa</span><span class="jp-step">04 Objetivo & OKR</span><span class="jp-step">05 Validação</span><span class="jp-step">06 Posicionamento</span><span class="jp-step">07 Estratégia</span></div>

    <div class="jp-panel"><h3>1. Desafios de crescimento</h3><p class="sub">Selecione quantos forem necessários. Cada item gera uma hipótese própria. As hipóteses depois são cruzadas para formar o diagnóstico.</p>
      <div class="jp-diagnostic">${journeyDiagnostics.map(x=>`<label class="jp-check ${journeyDiagState.selected[x[0]]?'selected':''}"><input type="checkbox" ${journeyDiagState.selected[x[0]]?'checked':''} onchange="toggleJourneyDiagnostic('${x[0]}')"><span><strong>${x[1]}</strong><small>${x[2]}</small></span></label>`).join('')}</div>
      <div class="jp-other"><input id="jpOtherInput" placeholder="Outro desafio que não está na lista..."><button class="btn" onclick="addJourneyOther()">＋ Adicionar</button></div><div class="jp-summary">${selectedCount?chips:'<span class="jp-tag">Nenhum desafio selecionado ainda</span>'}</div>
    </div>

    <div class="jp-panel"><div class="section-row"><div><h3>2. Hipóteses individuais</h3><p class="sub">Cada desafio selecionado produz uma hipótese. Nenhuma hipótese é tratada como fato antes da validação.</p></div><span class="jp-mini-badge">${d.hypotheses.length} hipótese(s)</span></div>
      <div class="jp-hyp-list">${d.hypotheses.map(h=>`<article class="jp-hyp"><div class="type">HIPÓTESE</div><strong>${h.title}</strong><p>${h.text}</p></article>`).join('')}</div>
    </div>

    <div class="jp-panel"><h3>3. Diagnóstico consolidado</h3><p class="sub">As hipóteses são conectadas para procurar relações, interdependências e efeitos sobre crescimento.</p>
      <div class="jp-diagnosis-chain"><span>DESAFIOS</span><b>→</b><span>HIPÓTESES</span><b>→</b><span>RELAÇÕES</span><b>→</b><span>DIAGNÓSTICO</span></div>
      <div class="jp-diagnosis-box"><div class="type">DIAGNÓSTICO · A VALIDAR</div><h3>${d.diagnosis}</h3></div>
      <div class="jp-intelligence"><div><b>DADO</b><p>O que o cliente informou e selecionou.</p></div><div><b>HIPÓTESE</b><p>Interpretação gerada a partir dos dados.</p></div><div><b>RECOMENDAÇÃO</b><p>Caminho sugerido, ainda sujeito à decisão.</p></div><div><b>DECISÃO</b><p>Só existe depois da validação humana.</p></div></div>
    </div>

    <div class="jp-panel"><h3>4. Justificativa estratégica</h3><p class="sub">O diagnóstico explica o cenário. A justificativa explica por que agir e por que a ordem de ação começa pela tração.</p><div class="jp-justification"><div class="type">JUSTIFICATIVA</div><p>${d.justification}</p></div>
      <div class="jp-priority-flow"><div><b>01 · TRAÇÃO</b><strong>Gerar leads</strong><small>Fazer a demanda aparecer.</small></div><div class="arrow">→</div><div><b>02 · ESTRUTURAÇÃO</b><strong>Organizar conversão</strong><small>Receber, qualificar e acompanhar.</small></div><div class="arrow">→</div><div><b>03 · PREVISIBILIDADE</b><strong>Otimizar</strong><small>Melhorar conversão e receita.</small></div></div>
    </div>

    <div class="jp-panel"><h3>5. Objetivo estratégico</h3><p class="sub">O objetivo traduz o diagnóstico em uma transformação que o projeto pretende produzir.</p><div class="jp-objective"><div class="type">OBJETIVO</div><h2>${d.objective}</h2></div>
      <div class="jp-okr"><div class="jp-okr-head"><div><span class="type">OKR · VERSÃO INICIAL</span><h3>Transformar aquisição em crescimento mais previsível</h3></div><span class="jp-mini-badge">A validar</span></div>
        <div class="jp-okr-grid"><article><div class="okr-label">KR · TRAÇÃO</div>${okrTraction.map(x=>`<p>□ ${x}</p>`).join('')}</article><article><div class="okr-label">KR · ESTRUTURAÇÃO</div>${okrStructure.map(x=>`<p>□ ${x}</p>`).join('')}</article></div>
        <small class="jp-note">Os números definitivos dos KRs devem ser definidos depois da validação do diagnóstico, posicionamento, capacidade operacional e dados disponíveis. O Studio não inventa metas críticas.</small>
      </div>
    </div>

    <div class="jp-panel"><h3>6. ICP e jornada inicial</h3><div class="jp-grid"><article class="jp-card"><div class="n">ICP</div><h4>Até 3 perfis prioritários</h4><p>Definir quem apresenta maior aderência ao problema, oferta, posicionamento e capacidade de atendimento.</p></article><article class="jp-card"><div class="n">JORNADA</div><h4>Da situação à decisão</h4><div class="jp-journey"><span>01 Descoberta<small>Reconhecer</small></span><span>02 Atenção<small>Entender</small></span><span>03 Consideração<small>Avaliar</small></span><span>04 Decisão<small>Agir</small></span><span>05 Pós-contato<small>Continuar</small></span></div></article></div></div>

    <div class="jp-panel"><h3>7. Pré-Projeto e gates</h3><p class="sub">O pré-projeto organiza a hipótese estratégica. O posicionamento continua sendo o gate antes da estratégia definitiva.</p><div class="jp-gate-flow"><span>BRIEFING</span><b>→</b><span>DIAGNÓSTICO</span><b>→</b><span>HIPÓTESES</span><b>→</b><span>JUSTIFICATIVA</span><b>→</b><span>OBJETIVO + OKR</span><b>→</b><span>VALIDAÇÃO</span><b>→</b><span>POSICIONAMENTO</span><b>→</b><span>ESTRATÉGIA</span></div>
      <div class="jp-gate"><div><strong>Gate de aprovação</strong><p>Pré-projeto aprovado → posicionamento → estratégia → jornada aprofundada → plano de comunicação → produção.</p></div><span id="jpGateLabel">AGUARDANDO VALIDAÇÃO</span></div></div>
  </div>`;
}
function toggleJourneyDiagnostic(id){journeyDiagState.selected[id]=!journeyDiagState.selected[id];renderJourneyArchitect();}
function addJourneyOther(){const input=$('jpOtherInput');if(!input)return;const value=input.value.trim();if(!value)return;journeyDiagState.other.push(value);renderJourneyArchitect();toast('Novo desafio adicionado ao diagnóstico.');}
function jpEditBrief(){const current='Dependência de indicação, previsibilidade comercial, estrutura de marketing e vendas.';const v=prompt('Adicione ou ajuste uma informação do briefing:',current);if(v!==null&&v.trim())toast('Informação registrada no briefing do projeto.');}
function jpApprove(){const s=$('jpStatus');if(s){s.textContent='APROVADO';s.style.background='#111';s.style.color='#fff'}const g=$('jpGateLabel');if(g)g.textContent='APROVADO';toast('Pré-projeto aprovado. Próximo gate: posicionamento de marca.');}
function jpPresent(){
 const w=window.open('','_blank');if(!w){toast('Permita pop-ups para abrir a apresentação.');return;} const d=buildDiagnosis();
 const hs=d.hypotheses.map(h=>`<div class="card"><b>${h.title}</b><p>${h.text}</p></div>`).join('');
 w.document.write(`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>Pré-Projeto — Mutuários Brasil</title><style>*{box-sizing:border-box}body{margin:0;font-family:Inter,Arial,sans-serif;color:#111;background:#f5f5f5}aside{position:fixed;left:0;top:0;bottom:0;width:235px;background:#111;color:#fff;padding:25px 15px}aside b{display:block;margin:0 10px 25px;font-size:13px}aside a{display:block;color:#aaa;text-decoration:none;padding:10px;border-radius:8px;font-size:10px}aside a:hover{background:#222;color:#fff}main{margin-left:235px}section{min-height:100vh;background:#fff;padding:70px 8vw;display:flex;flex-direction:column;justify-content:center;border-bottom:1px solid #eee}.dark{background:#111;color:#fff}.k{font-size:9px;letter-spacing:.16em;color:#999;font-weight:800}.dark .k{color:#aaa}h1{font-size:60px;line-height:.98;letter-spacing:-3px;margin:15px 0}h2{font-size:40px;letter-spacing:-1.5px}.lead{font-size:17px;line-height:1.7;color:#555;max-width:850px}.dark .lead{color:#bbb}.cards{display:grid;grid-template-columns:1fr 1fr;gap:10px;max-width:950px}.card{border:1px solid #e6e6e6;border-radius:12px;padding:18px}.card b{font-size:12px}.card p{font-size:11px;line-height:1.55;color:#666}.flow{display:flex;gap:6px;flex-wrap:wrap}.flow span{border:1px solid #ddd;border-radius:999px;padding:9px 12px;background:#fafafa;font-size:9px}.okr{display:grid;grid-template-columns:1fr 1fr;gap:15px}.okr>div{border:1px solid #ddd;padding:20px;border-radius:14px}.objective{border-left:4px solid #111;padding:15px 20px;max-width:900px}.objective h3{font-size:25px;margin:0}.muted{color:#666}@media(max-width:760px){aside{display:none}main{margin:0}section{padding:45px 25px}h1{font-size:42px}.cards,.okr{grid-template-columns:1fr}}</style><style>
.jp-mini-badge{display:inline-flex;align-items:center;border:1px solid #ddd;background:#fafafa;border-radius:999px;padding:7px 10px;font-size:9px;color:#666;font-weight:700}
.jp-hyp-list{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.jp-hyp{border:1px solid #e8e8e8;border-radius:12px;padding:16px;background:#fff}.jp-hyp .type,.jp-diagnosis-box .type,.jp-justification .type,.jp-objective .type,.jp-okr .type{font-size:9px;letter-spacing:.12em;color:#999;font-weight:800;margin-bottom:8px}.jp-hyp strong{font-size:12px}.jp-hyp p{font-size:11px;line-height:1.55;color:#666;margin:8px 0 0}
.jp-diagnosis-chain,.jp-gate-flow{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:12px 0}.jp-diagnosis-chain span,.jp-gate-flow span{border:1px solid #ddd;background:#fafafa;border-radius:999px;padding:8px 11px;font-size:9px;font-weight:700}.jp-diagnosis-chain b,.jp-gate-flow b{color:#aaa}.jp-diagnosis-box{border:1px solid #111;background:#fafafa;border-radius:14px;padding:20px;margin-top:15px}.jp-diagnosis-box h3{font-size:17px;line-height:1.45;margin:0;font-weight:650}.jp-intelligence{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:10px}.jp-intelligence>div{border:1px solid #eee;border-radius:10px;padding:12px}.jp-intelligence b{font-size:9px}.jp-intelligence p{font-size:10px;color:#777;line-height:1.4;margin:6px 0 0}.jp-justification{border-left:3px solid #111;background:#fafafa;padding:18px 20px;border-radius:0 12px 12px 0}.jp-justification p{font-size:13px;line-height:1.65;margin:0;color:#333}.jp-priority-flow{display:grid;grid-template-columns:1fr auto 1fr auto 1fr;align-items:center;gap:10px;margin-top:15px}.jp-priority-flow>div:not(.arrow){border:1px solid #eee;border-radius:12px;padding:15px;background:#fff}.jp-priority-flow b{font-size:9px;color:#999;display:block}.jp-priority-flow strong{font-size:14px;display:block;margin:5px 0}.jp-priority-flow small{font-size:10px;color:#777}.jp-priority-flow .arrow{font-size:20px;color:#aaa}.jp-objective{border:1px solid #111;border-radius:14px;padding:20px;background:#fff}.jp-objective h2{font-size:22px;line-height:1.35;margin:0;max-width:900px}.jp-okr{margin-top:15px;border:1px solid #e5e5e5;border-radius:14px;padding:18px;background:#fafafa}.jp-okr-head{display:flex;justify-content:space-between;gap:15px;align-items:flex-start}.jp-okr-head h3{margin:4px 0 0;font-size:16px}.jp-okr-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:15px}.jp-okr-grid article{background:#fff;border:1px solid #eee;border-radius:10px;padding:14px}.okr-label{font-size:9px;font-weight:800;letter-spacing:.1em;color:#777;margin-bottom:8px}.jp-okr-grid p{font-size:10px;color:#555;line-height:1.5;margin:7px 0}.jp-note{display:block;color:#999;font-size:9px;line-height:1.45;margin-top:12px}.jp-wrap .jp-panel h3{margin-bottom:4px}@media(max-width:900px){.jp-hyp-list,.jp-intelligence{grid-template-columns:1fr 1fr}.jp-priority-flow{grid-template-columns:1fr}.jp-priority-flow .arrow{display:none}}@media(max-width:760px){.jp-hyp-list,.jp-intelligence,.jp-okr-grid{grid-template-columns:1fr}.jp-priority-flow{grid-template-columns:1fr}}
</style>
<style>
.architecture-overview{margin:24px 0 8px;padding:22px;border:1px solid #eee;background:#fff;border-radius:16px}.architecture-overview .section-row{margin-bottom:16px}.architecture-flow{display:flex;flex-wrap:wrap;align-items:center;gap:7px;padding:14px;border:1px solid #eee;background:#fafafa;border-radius:12px;font-size:10px;font-weight:700;color:#555}.architecture-flow div{padding:7px 9px;background:#fff;border:1px solid #e7e7e7;border-radius:999px}.architecture-flow b{color:#aaa}.architecture-split{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:12px}.architecture-split article{padding:15px;border:1px solid #eee;border-radius:12px;background:#fff}.architecture-split span{font-size:9px;color:#999;letter-spacing:.08em}.architecture-split strong{display:block;font-size:15px;margin:6px 0}.architecture-split p{margin:0;color:#666;font-size:12px;line-height:1.5}@media(max-width:760px){.architecture-split{grid-template-columns:1fr}.architecture-flow{gap:5px}}
</style></head><body><aside><b>AMPLIAÇÃO STUDIO</b><a href="#capa">Capa</a><a href="#diagnostico">Diagnóstico</a><a href="#hipoteses">Hipóteses</a><a href="#objetivo">Objetivo & OKR</a><a href="#jornada">Jornada</a><a href="#gates">Gates</a></aside><main>
 <section id="capa" class="dark"><div class="k">PRÉ-PROJETO · MUTUÁRIOS BRASIL</div><h1>Jornada de Crescimento</h1><p class="lead">Do diagnóstico à definição do objetivo, com prioridade inicial em geração de demanda e estruturação progressiva da conversão.</p></section>
 <section id="diagnostico"><div class="k">01 · DIAGNÓSTICO</div><h2>Desafios selecionados</h2><div class="cards">${d.selected.map(x=>`<div class="card"><b>${x[1]}</b><p>${x[2]}</p></div>`).join('')}</div><div class="objective" style="margin-top:25px"><p>${d.diagnosis}</p></div></section>
 <section id="hipoteses"><div class="k">02 · HIPÓTESES</div><h2>Cada desafio gera uma hipótese</h2><div class="cards">${hs}</div><p class="muted">Hipóteses precisam ser validadas; não são conclusões definitivas.</p></section>
 <section id="objetivo"><div class="k">03 · JUSTIFICATIVA · OBJETIVO · OKR</div><h2>Começar pela tração</h2><p class="lead">${d.justification}</p><div class="objective"><h3>${d.objective}</h3></div><div class="okr" style="margin-top:25px"><div><b>KR · TRAÇÃO</b><p>Definir meta inicial de leads qualificados.</p><p>Colocar canal de aquisição em operação.</p><p>Medir volume, qualidade e origem.</p></div><div><b>KR · ESTRUTURAÇÃO</b><p>Registrar os leads recebidos.</p><p>Definir qualificação e responsáveis.</p><p>Acompanhar conversão por etapa.</p></div></div></section>
 <section id="jornada"><div class="k">04 · JORNADA</div><h2>Da situação à decisão</h2><div class="flow"><span>01 Descoberta</span><span>02 Atenção</span><span>03 Consideração</span><span>04 Decisão</span><span>05 Pós-contato</span></div></section>
 <section id="gates"><div class="k">05 · GATES</div><h2>O que acontece depois</h2><p class="lead">Validação → Posicionamento → Estratégia → Jornada aprofundada → Plano de Comunicação → Produção.</p></section></main></body></html>`);w.document.close();}
function jpPDF(){const w=window.open('','_blank');if(!w){toast('Permita pop-ups para gerar o PDF.');return;}const d=buildDiagnosis();w.document.write(`<html><head><title>Pré-Projeto — Mutuários Brasil</title><style>body{font-family:Arial;padding:35px;color:#111}h1{font-size:30px}h2{font-size:22px;margin-top:28px}.box{border:1px solid #ddd;padding:14px;margin:8px 0;border-radius:8px}.label{font-size:10px;letter-spacing:.12em;color:#888;font-weight:bold}p{line-height:1.6;color:#555}@media print{.box{break-inside:avoid}}</style><style>
.jp-mini-badge{display:inline-flex;align-items:center;border:1px solid #ddd;background:#fafafa;border-radius:999px;padding:7px 10px;font-size:9px;color:#666;font-weight:700}
.jp-hyp-list{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.jp-hyp{border:1px solid #e8e8e8;border-radius:12px;padding:16px;background:#fff}.jp-hyp .type,.jp-diagnosis-box .type,.jp-justification .type,.jp-objective .type,.jp-okr .type{font-size:9px;letter-spacing:.12em;color:#999;font-weight:800;margin-bottom:8px}.jp-hyp strong{font-size:12px}.jp-hyp p{font-size:11px;line-height:1.55;color:#666;margin:8px 0 0}
.jp-diagnosis-chain,.jp-gate-flow{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:12px 0}.jp-diagnosis-chain span,.jp-gate-flow span{border:1px solid #ddd;background:#fafafa;border-radius:999px;padding:8px 11px;font-size:9px;font-weight:700}.jp-diagnosis-chain b,.jp-gate-flow b{color:#aaa}.jp-diagnosis-box{border:1px solid #111;background:#fafafa;border-radius:14px;padding:20px;margin-top:15px}.jp-diagnosis-box h3{font-size:17px;line-height:1.45;margin:0;font-weight:650}.jp-intelligence{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:10px}.jp-intelligence>div{border:1px solid #eee;border-radius:10px;padding:12px}.jp-intelligence b{font-size:9px}.jp-intelligence p{font-size:10px;color:#777;line-height:1.4;margin:6px 0 0}.jp-justification{border-left:3px solid #111;background:#fafafa;padding:18px 20px;border-radius:0 12px 12px 0}.jp-justification p{font-size:13px;line-height:1.65;margin:0;color:#333}.jp-priority-flow{display:grid;grid-template-columns:1fr auto 1fr auto 1fr;align-items:center;gap:10px;margin-top:15px}.jp-priority-flow>div:not(.arrow){border:1px solid #eee;border-radius:12px;padding:15px;background:#fff}.jp-priority-flow b{font-size:9px;color:#999;display:block}.jp-priority-flow strong{font-size:14px;display:block;margin:5px 0}.jp-priority-flow small{font-size:10px;color:#777}.jp-priority-flow .arrow{font-size:20px;color:#aaa}.jp-objective{border:1px solid #111;border-radius:14px;padding:20px;background:#fff}.jp-objective h2{font-size:22px;line-height:1.35;margin:0;max-width:900px}.jp-okr{margin-top:15px;border:1px solid #e5e5e5;border-radius:14px;padding:18px;background:#fafafa}.jp-okr-head{display:flex;justify-content:space-between;gap:15px;align-items:flex-start}.jp-okr-head h3{margin:4px 0 0;font-size:16px}.jp-okr-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:15px}.jp-okr-grid article{background:#fff;border:1px solid #eee;border-radius:10px;padding:14px}.okr-label{font-size:9px;font-weight:800;letter-spacing:.1em;color:#777;margin-bottom:8px}.jp-okr-grid p{font-size:10px;color:#555;line-height:1.5;margin:7px 0}.jp-note{display:block;color:#999;font-size:9px;line-height:1.45;margin-top:12px}.jp-wrap .jp-panel h3{margin-bottom:4px}@media(max-width:900px){.jp-hyp-list,.jp-intelligence{grid-template-columns:1fr 1fr}.jp-priority-flow{grid-template-columns:1fr}.jp-priority-flow .arrow{display:none}}@media(max-width:760px){.jp-hyp-list,.jp-intelligence,.jp-okr-grid{grid-template-columns:1fr}.jp-priority-flow{grid-template-columns:1fr}}
</style>
<style>
.architecture-overview{margin:24px 0 8px;padding:22px;border:1px solid #eee;background:#fff;border-radius:16px}.architecture-overview .section-row{margin-bottom:16px}.architecture-flow{display:flex;flex-wrap:wrap;align-items:center;gap:7px;padding:14px;border:1px solid #eee;background:#fafafa;border-radius:12px;font-size:10px;font-weight:700;color:#555}.architecture-flow div{padding:7px 9px;background:#fff;border:1px solid #e7e7e7;border-radius:999px}.architecture-flow b{color:#aaa}.architecture-split{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:12px}.architecture-split article{padding:15px;border:1px solid #eee;border-radius:12px;background:#fff}.architecture-split span{font-size:9px;color:#999;letter-spacing:.08em}.architecture-split strong{display:block;font-size:15px;margin:6px 0}.architecture-split p{margin:0;color:#666;font-size:12px;line-height:1.5}@media(max-width:760px){.architecture-split{grid-template-columns:1fr}.architecture-flow{gap:5px}}
</style></head><body><h1>Pré-Projeto — Jornada de Crescimento</h1><p>Mutuários Brasil · Ampliação Studio</p><h2>Diagnóstico</h2><div class="box">${d.diagnosis}</div><h2>Hipóteses</h2>${d.hypotheses.map(h=>`<div class="box"><b>${h.title}</b><p>${h.text}</p></div>`).join('')}<h2>Justificativa</h2><div class="box">${d.justification}</div><h2>Objetivo</h2><div class="box"><b>${d.objective}</b></div><h2>OKR inicial</h2><div class="box"><div class="label">TRAÇÃO</div><p>Meta inicial de leads qualificados · canal de aquisição em operação · medir volume, qualidade e origem.</p></div><div class="box"><div class="label">ESTRUTURAÇÃO</div><p>Registrar leads · definir qualificação e responsáveis · acompanhar conversão por etapa.</p></div><h2>Gates</h2><p>Validação → Posicionamento → Estratégia → Jornada aprofundada → Plano de Comunicação → Produção.</p></body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),400);}

