/* ===== Landing pages: tipos de produto → estrutura de blocos → texto (IA, a partir dos insumos do projeto) → HTML responsivo exportável.
   As estruturas abaixo são uma proposta de partida (curso online, e-book, serviço, evento): ajuste LP_TYPES quando houver modelos de referência. ===== */
const LP_TYPE_INFO = {
  curso: {label: 'Curso online', blocks: ['hero', 'dor', 'solucao', 'conteudo', 'para_quem', 'autoridade', 'prova', 'bonus', 'oferta', 'garantia', 'faq', 'cta_final'], goal: 'checkout', cta: 'Quero me inscrever',
    why: 'Quem compra curso precisa acreditar que o método funciona e que vai conseguir: promessa → dor → método → o que vai aprender → para quem é → professor → prova → oferta e garantia.'},
  ebook: {label: 'E-book', blocks: ['hero', 'dor', 'conteudo', 'autoridade', 'prova', 'oferta', 'faq', 'cta_final'], goal: 'checkout', cta: 'Quero o e-book',
    why: 'Produto de decisão rápida: página curta. Capa e promessa no topo, o que tem dentro (capítulos), quem escreveu, prova e oferta.'},
  servico: {label: 'Serviço', blocks: ['hero', 'dor', 'solucao', 'passos', 'beneficios', 'prova', 'autoridade', 'faq', 'form'], goal: 'lead', cta: 'Falar com a equipe',
    why: 'Serviço se vende por confiança: problema → como resolvemos → etapas → resultado → provas reais → equipe → perguntas → contato (formulário/WhatsApp).'},
  evento: {label: 'Evento', blocks: ['hero', 'numeros', 'texto', 'programa', 'palestrantes', 'local', 'ingressos', 'prova', 'faq', 'cta_final'], goal: 'checkout', cta: 'Garantir meu ingresso',
    why: 'Evento precisa de data, local e programa visíveis logo no começo, contagem regressiva, quem vai estar lá, lotes e urgência honesta.'},
  cadastro: {label: 'Cadastro / solicitação gratuita', blocks: ['hero', 'passos', 'beneficios', 'prova', 'faq', 'form'], goal: 'lead', cta: 'Quero me cadastrar',
    why: 'Página de uma ação só: pedir algo gratuito (visita, exemplar, aula, avaliação). Promessa clara no topo, o que acontece depois do cadastro (etapas), por que vale, prova e perguntas, e o formulário curto (nome, contato e consentimento).'},
  generico: {label: 'Captação simples', blocks: ['hero', 'beneficios', 'prova', 'form'], goal: 'lead', cta: 'Quero receber', why: 'Página curta de captação de lead: promessa, benefícios, prova e formulário.'}
};
/* campos de cada bloco (editor e IA): [campo, rótulo, tipo] — tipos: line, area, items(rótulo do t / rótulo do d), list, img */
const LP_BLOCK = {
  hero: {label: 'Topo (promessa)', fields: [['kicker', 'Etiqueta (acima do título)', 'line'], ['title', 'Título', 'area'], ['text', 'Subtítulo', 'area'], ['cta', 'Botão', 'line'], ['note', 'Nota abaixo do botão', 'line'], ['imgId', 'Imagem', 'img']], ai: 'title: promessa específica (até 80 caracteres); text: subtítulo que explica para quem e como (até 180); cta: texto do botão; note: microtexto de segurança/condição (opcional); kicker: etiqueta curta'},
  numeros: {label: 'Números / destaques', fields: [['items', 'Itens', 'items:Valor/Legenda']], ai: 'items: 3 a 4 números ou fatos verificáveis do insumo (t = valor, d = legenda). Sem número no insumo, use [CONFIRMAR: …]'},
  dor: {label: 'Problema / dor', fields: [['title', 'Título', 'line'], ['text', 'Texto', 'area'], ['items', 'Sinais da dor', 'items:Situação/Detalhe']], ai: 'title; text: 1 parágrafo; items: 3 a 5 situações reconhecíveis (t) com detalhe opcional (d)'},
  solucao: {label: 'Solução / método', fields: [['title', 'Título', 'line'], ['text', 'Texto', 'area'], ['items', 'Pilares', 'items:Pilar/Explicação']], ai: 'title; text: como funciona em um parágrafo; items: 3 pilares (t, d)'},
  beneficios: {label: 'Benefícios', fields: [['title', 'Título', 'line'], ['items', 'Benefícios', 'items:Benefício/Explicação']], ai: 'title; items: 3 a 6 benefícios concretos (t, d), sem promessa absoluta'},
  passos: {label: 'Como funciona (etapas)', fields: [['title', 'Título', 'line'], ['items', 'Etapas', 'items:Etapa/Descrição']], ai: 'title; items: 3 a 5 etapas na ordem (t, d)'},
  conteudo: {label: 'Conteúdo (módulos / capítulos)', fields: [['title', 'Título', 'line'], ['items', 'Módulos ou capítulos', 'items:Nome/O que tem dentro']], ai: 'title; items: módulos ou capítulos reais do insumo (t = nome, d = o que a pessoa aprende). Não invente conteúdo que não esteja no insumo'},
  para_quem: {label: 'Para quem é', fields: [['title', 'Título', 'line'], ['yes', 'É para você se…', 'list'], ['no', 'Não é para você se…', 'list']], ai: 'title; yes: 3 a 5 perfis; no: 2 a 3 perfis'},
  autoridade: {label: 'Quem está por trás', fields: [['title', 'Título', 'line'], ['name', 'Nome', 'line'], ['text', 'Apresentação', 'area'], ['imgId', 'Foto', 'img']], ai: 'title; name; text: apresentação curta com credenciais SÓ do insumo; sem inventar formação, tempo de experiência ou números'},
  prova: {label: 'Prova (depoimentos / casos)', fields: [['title', 'Título', 'line'], ['items', 'Depoimentos', 'items:Depoimento/Quem disse']], ai: 'title; items: NÃO invente depoimentos. Use o que existir no insumo; onde faltar, escreva "[CONFIRMAR: depoimento real de cliente]" em t e "[CONFIRMAR: nome]" em d'},
  oferta: {label: 'Oferta e preço', fields: [['title', 'Título', 'line'], ['text', 'Texto', 'area'], ['items', 'O que está incluso', 'items:Item/Detalhe'], ['price', 'Preço', 'line'], ['note', 'Condição de pagamento', 'line'], ['cta', 'Botão', 'line']], ai: 'title; text; items: o que está incluso (do insumo); price e note: use exatamente o preço informado, ou "[CONFIRMAR: preço]"; cta'},
  bonus: {label: 'Bônus', fields: [['title', 'Título', 'line'], ['items', 'Bônus', 'items:Bônus/Descrição']], ai: 'title; items: só bônus que existam no insumo; sem bônus, retorne lista vazia'},
  garantia: {label: 'Garantia', fields: [['title', 'Título', 'line'], ['text', 'Texto', 'area']], ai: 'title; text: use a garantia do insumo (prazo, condição). Sem informação: "[CONFIRMAR: política de garantia]"'},
  faq: {label: 'Perguntas frequentes', fields: [['title', 'Título', 'line'], ['items', 'Perguntas', 'items:Pergunta/Resposta']], ai: 'title; items: 4 a 6 perguntas que travam a decisão (t = pergunta, d = resposta honesta, sem inventar regras)'},
  programa: {label: 'Programa / agenda', fields: [['title', 'Título', 'line'], ['items', 'Atividades', 'items:Horário/Atividade']], ai: 'title; items: programação do insumo (t = horário ou dia, d = atividade). Sem programação: "[CONFIRMAR: horário]"'},
  palestrantes: {label: 'Quem vai estar', fields: [['title', 'Título', 'line'], ['items', 'Pessoas', 'items:Nome/Mini bio']], ai: 'title; items: pessoas do insumo (t = nome, d = bio curta); sem nomes: "[CONFIRMAR: nome]"'},
  local: {label: 'Data e local', fields: [['title', 'Título', 'line'], ['text', 'Endereço / como chegar / link online', 'area'], ['note', 'Data e hora', 'line']], ai: 'title; text: endereço ou formato online; note: data e hora (do insumo)'},
  ingressos: {label: 'Ingressos / lotes', fields: [['title', 'Título', 'line'], ['items', 'Lotes', 'items:Lote/Valor e condição'], ['cta', 'Botão', 'line']], ai: 'title; items: lotes do insumo (t = nome, d = valor e condição); sem valores: "[CONFIRMAR: valor]"; cta'},
  texto: {label: 'Texto livre / sobre', fields: [['title', 'Título', 'line'], ['text', 'Texto', 'area']], ai: 'title; text: 1 a 2 parágrafos'},
  cta_final: {label: 'Chamada final', fields: [['title', 'Título', 'line'], ['text', 'Texto', 'area'], ['cta', 'Botão', 'line']], ai: 'title; text: fecha a decisão sem pressão falsa; cta'},
  form: {label: 'Formulário de contato', fields: [['title', 'Título', 'line'], ['text', 'Texto', 'area'], ['cta', 'Botão', 'line']], ai: 'title; text: o que acontece depois de enviar; cta'}
};
const lpBlockNew = t => Object.assign({id: uid('bk'), t, on: true, title: '', text: '', kicker: '', cta: '', note: '', name: '', price: '', imgId: '', items: [], yes: [], no: []}, {});
const lpStructure = type => (LP_TYPE_INFO[type] || LP_TYPE_INFO.generico).blocks.map(lpBlockNew);

/* texto de partida quando a IA não está disponível: usa o que o projeto já tem */
function lpSeedBlocks(l) {
  const bl = lpStructure(l.type || 'generico'), P = l.product, by = t => bl.find(b => b.t === t);
  const h = by('hero'); if (h) { h.title = l.headline || P.nome || ''; h.text = l.sub || ''; h.cta = l.cta || LP_TYPE_INFO[l.type || 'generico'].cta; }
  const be = by('beneficios'); if (be && l.bullets) be.items = l.bullets.split('\n').map(x => x.trim()).filter(Boolean).map(t => ({t, d: ''}));
  return bl;
}

/* ---------- renderização do HTML ---------- */
const lpE = s => String(s == null ? '' : s).replace(/[&<>"']/g, c => ({'&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'})[c]);
const lpRich = s => lpE(s).replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>').replace(/\n/g, '<br>');
const lpPending = l => (l.blocks || []).filter(b => b.on).reduce((n, b) => n + (JSON.stringify([b.title, b.text, b.note, b.price, b.items, b.yes, b.no]).match(/\[CONFIRMAR/g) || []).length, 0);
function lpCta(l, b) {
  const P = l.product, hasForm = (l.blocks || []).some(x => x.t === 'form' && x.on);
  if (P.checkout && l.type !== 'servico') return {href: P.checkout, ext: true};
  if (hasForm) return {href: '#form', ext: false};
  if (l.whatsapp) return {href: 'https://wa.me/' + l.whatsapp + '?text=' + encodeURIComponent('Olá! Vim pela página: ' + (l.name || '')), ext: true};
  return {href: P.checkout || '#', ext: !!P.checkout};
}
async function lpImg(id) { if (!id) return ''; try { const b = await imgGet(id); if (!b) return ''; return (await ailBlob(b, 1200)).url; } catch (e) { return ''; } }
function lpFontsLink(th) { const f = [...new Set([th.head, th.body])].filter(Boolean).map(x => 'family=' + encodeURIComponent(x).replace(/%20/g, '+') + ':wght@400;600;700;800').join('&'); return f ? `<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?${f}&display=swap">` : ''; }
function lpCss(th) {
  const dark = th.dark, bg = dark ? '#0e0e10' : th.bg, fg = dark ? '#f5f5f5' : th.fg, soft = dark ? '#18181b' : 'color-mix(in srgb,' + th.bg + ' 94%,' + th.fg + ')', line = dark ? '#2a2a2f' : 'color-mix(in srgb,' + th.fg + ' 14%,transparent)', mut = dark ? '#a1a1aa' : 'color-mix(in srgb,' + th.fg + ' 62%,' + th.bg + ')';
  return `:root{--a:${th.accent};--bg:${bg};--fg:${fg};--soft:${soft};--line:${line};--mut:${mut}}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--fg);font:17px/1.6 '${th.body}',system-ui,-apple-system,Segoe UI,Roboto,sans-serif;-webkit-font-smoothing:antialiased}
h1,h2,h3{font-family:'${th.head}','${th.body}',system-ui,sans-serif;line-height:1.12;margin:0 0 .5em;letter-spacing:-.01em}h1{font-size:clamp(32px,6vw,58px);font-weight:800}h2{font-size:clamp(25px,4vw,38px);font-weight:800}h3{font-size:19px;font-weight:700}p{margin:0 0 1em}
.w{max-width:1040px;margin:0 auto;padding:0 22px}section{padding:clamp(44px,7vw,84px) 0}section.alt{background:var(--soft)}.k{display:inline-block;font-size:12px;letter-spacing:.12em;text-transform:uppercase;font-weight:700;color:var(--a);margin-bottom:12px}.mut{color:var(--mut)}
.btn{display:inline-block;background:var(--a);color:#fff;text-decoration:none;font-weight:700;padding:16px 30px;border-radius:12px;font-size:17px;border:0;cursor:pointer;font-family:inherit;box-shadow:0 8px 24px color-mix(in srgb,var(--a) 35%,transparent);transition:transform .15s}.btn:hover{transform:translateY(-2px)}.note{font-size:13px;color:var(--mut);margin-top:10px}
.hero{padding:clamp(48px,8vw,100px) 0}.hero .g{display:grid;grid-template-columns:1.1fr .9fr;gap:40px;align-items:center}.hero.noimg .g{grid-template-columns:1fr;max-width:760px}.hero img{width:100%;border-radius:18px;display:block;box-shadow:0 20px 60px rgba(0,0,0,.18)}.hero p.sub{font-size:clamp(18px,2.4vw,22px);color:var(--mut)}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:18px;margin-top:24px}.card{background:var(--bg);border:1px solid var(--line);border-radius:16px;padding:22px}section.alt .card{background:var(--bg)}.card h3{margin-bottom:.35em}.card p{margin:0;color:var(--mut);font-size:15.5px}
.num{font-size:clamp(34px,5vw,48px);font-weight:800;color:var(--a);font-family:'${th.head}',sans-serif;line-height:1}.step{counter-increment:s}.step::before{content:counter(s);display:grid;place-items:center;width:34px;height:34px;border-radius:50%;background:var(--a);color:#fff;font-weight:800;margin-bottom:12px}.steps{counter-reset:s}
ul.ck{list-style:none;padding:0;margin:14px 0 0}ul.ck li{padding:6px 0 6px 30px;position:relative}ul.ck li::before{content:'✓';position:absolute;left:0;color:var(--a);font-weight:800}ul.ck.no li::before{content:'✕';color:#b3261e}
.q{font-size:18px;font-style:italic;margin-bottom:10px}.price{font-size:clamp(38px,6vw,56px);font-weight:800;font-family:'${th.head}',sans-serif;color:var(--a)}.box{background:var(--bg);border:2px solid var(--a);border-radius:20px;padding:clamp(24px,4vw,40px);max-width:640px;margin:20px auto 0;text-align:center}.box ul.ck{text-align:left;display:inline-block}
details{border-bottom:1px solid var(--line);padding:14px 0}summary{cursor:pointer;font-weight:700;font-size:18px;list-style:none}summary::-webkit-details-marker{display:none}summary::after{content:'+';float:right;color:var(--a);font-size:22px}details[open] summary::after{content:'–'}details p{margin:10px 0 0;color:var(--mut)}
.tl{border-left:3px solid var(--a);padding-left:18px;margin:0 0 18px}.tl b{display:block;color:var(--a)}.center{text-align:center}.cd{display:flex;gap:12px;margin:18px 0}.cd div{background:var(--soft);border:1px solid var(--line);border-radius:12px;padding:10px 14px;text-align:center;min-width:64px}.cd b{display:block;font-size:26px;font-family:'${th.head}',sans-serif}.cd small{font-size:11px;color:var(--mut);text-transform:uppercase}
form{max-width:480px;display:grid;gap:12px;margin-top:18px}.center form{margin-left:auto;margin-right:auto;text-align:left}input,textarea{width:100%;padding:14px;border:1px solid var(--line);border-radius:10px;font:inherit;background:var(--bg);color:var(--fg)}.hp{position:absolute;left:-9999px}.lg{font-size:12.5px;color:var(--mut);display:flex;gap:8px;align-items:flex-start}.lg input{width:auto;margin-top:3px}#ok{display:none;background:#e6f6ea;color:#176b30;padding:12px;border-radius:10px}.wa{display:inline-block;margin-top:12px;font-weight:700;color:var(--a)}
footer{padding:34px 0;border-top:1px solid var(--line);font-size:13px;color:var(--mut)}.bar{display:none;position:fixed;left:0;right:0;bottom:0;padding:10px 14px;background:var(--bg);border-top:1px solid var(--line);z-index:50}.bar .btn{display:block;text-align:center;padding:14px}
@media(max-width:760px){.hero .g{grid-template-columns:1fr}.bar{display:block}body{padding-bottom:74px}.btn{width:100%;text-align:center}}`;
}
function lpBlockHTML(l, b, ctx) {
  const E = lpE, R = lpRich, cta = lpCta(l, b), btn = (txt, id) => `<a class="btn" href="${E(cta.href)}"${cta.ext ? ' target="_blank" rel="noopener"' : ''}${id ? ' id="' + id + '"' : ''}>${E(txt || LP_TYPE_INFO[l.type || 'generico'].cta)}</a>`;
  const head = (extra) => (b.title ? `<h2>${R(b.title)}</h2>` : '') + (extra || ''), items = (cls, fn) => `<div class="grid ${cls || ''}">${b.items.filter(i => i.t || i.d).map(fn).join('')}</div>`;
  const card = i => `<div class="card">${i.t ? `<h3>${R(i.t)}</h3>` : ''}${i.d ? `<p>${R(i.d)}</p>` : ''}</div>`;
  switch (b.t) {
    case 'hero': return `<header class="hero ${ctx.img ? '' : 'noimg'}"><div class="w"><div class="g"><div>${b.kicker ? `<span class="k">${E(b.kicker)}</span>` : ''}<h1>${R(b.title)}</h1>${b.text ? `<p class="sub">${R(b.text)}</p>` : ''}${ctx.countdown}${btn(b.cta, 'cta1')}${b.note ? `<div class="note">${E(b.note)}</div>` : ''}</div>${ctx.img ? `<div><img src="${ctx.img}" alt="${E(b.title)}"></div>` : ''}</div></div></header>`;
    case 'numeros': return `<section class="alt"><div class="w center"><div class="grid">${b.items.filter(i => i.t).map(i => `<div><div class="num">${E(i.t)}</div><div class="mut">${E(i.d)}</div></div>`).join('')}</div></div></section>`;
    case 'dor': return `<section><div class="w">${head(b.text ? `<p class="mut">${R(b.text)}</p>` : '')}${b.items.length ? `<ul class="ck no">${b.items.filter(i => i.t).map(i => `<li><strong>${R(i.t)}</strong>${i.d ? ' ' + R(i.d) : ''}</li>`).join('')}</ul>` : ''}</div></section>`;
    case 'solucao': return `<section class="alt"><div class="w">${head(b.text ? `<p class="mut">${R(b.text)}</p>` : '')}${items('', card)}</div></section>`;
    case 'beneficios': return `<section><div class="w">${head()}${items('', card)}</div></section>`;
    case 'passos': return `<section class="alt"><div class="w">${head()}<div class="grid steps">${b.items.filter(i => i.t || i.d).map(i => `<div class="card step">${i.t ? `<h3>${R(i.t)}</h3>` : ''}${i.d ? `<p>${R(i.d)}</p>` : ''}</div>`).join('')}</div></div></section>`;
    case 'conteudo': return `<section><div class="w">${head()}${items('', i => `<div class="card"><h3>${R(i.t)}</h3>${i.d ? `<p>${R(i.d)}</p>` : ''}</div>`)}</div></section>`;
    case 'para_quem': return `<section class="alt"><div class="w">${head()}<div class="grid"><div class="card"><h3>É para você se…</h3><ul class="ck">${b.yes.map(x => `<li>${R(x)}</li>`).join('')}</ul></div>${b.no.length ? `<div class="card"><h3>Não é para você se…</h3><ul class="ck no">${b.no.map(x => `<li>${R(x)}</li>`).join('')}</ul></div>` : ''}</div></div></section>`;
    case 'autoridade': return `<section><div class="w"><div class="hero ${ctx.img ? '' : 'noimg'}" style="padding:0"><div class="g" style="grid-template-columns:${ctx.img ? '.4fr 1fr' : '1fr'}">${ctx.img ? `<div><img src="${ctx.img}" alt="${E(b.name)}" style="border-radius:50%;aspect-ratio:1;object-fit:cover"></div>` : ''}<div>${head()}${b.name ? `<p><strong>${E(b.name)}</strong></p>` : ''}<p class="mut">${R(b.text)}</p></div></div></div></div></section>`;
    case 'prova': return `<section class="alt"><div class="w">${head()}${items('', i => `<div class="card"><p class="q">“${R(i.t)}”</p><p><strong>${R(i.d)}</strong></p></div>`)}</div></section>`;
    case 'oferta': return `<section id="oferta"><div class="w center">${head(b.text ? `<p class="mut">${R(b.text)}</p>` : '')}<div class="box">${b.items.length ? `<ul class="ck">${b.items.filter(i => i.t).map(i => `<li><strong>${R(i.t)}</strong>${i.d ? ' ' + R(i.d) : ''}</li>`).join('')}</ul>` : ''}${b.price ? `<div class="price">${E(b.price)}</div>` : ''}${b.note ? `<div class="note" style="margin:0 0 16px">${E(b.note)}</div>` : ''}${btn(b.cta)}</div></div></section>`;
    case 'bonus': return b.items.some(i => i.t) ? `<section class="alt"><div class="w">${head()}${items('', card)}</div></section>` : '';
    case 'garantia': return `<section><div class="w center" style="max-width:720px">${head(`<p class="mut">${R(b.text)}</p>`)}</div></section>`;
    case 'faq': return `<section><div class="w" style="max-width:780px">${head()}${b.items.filter(i => i.t).map(i => `<details><summary>${R(i.t)}</summary><p>${R(i.d)}</p></details>`).join('')}</div></section>`;
    case 'programa': return `<section class="alt"><div class="w" style="max-width:780px">${head()}${b.items.filter(i => i.t || i.d).map(i => `<div class="tl"><b>${E(i.t)}</b>${R(i.d)}</div>`).join('')}</div></section>`;
    case 'palestrantes': return `<section><div class="w">${head()}${items('', card)}</div></section>`;
    case 'local': return `<section class="alt"><div class="w center" style="max-width:760px">${head(b.note ? `<p><strong>${E(b.note)}</strong></p>` : '')}<p class="mut">${R(b.text)}</p></div></section>`;
    case 'ingressos': return `<section id="ingressos"><div class="w center">${head()}${items('', i => `<div class="card"><h3>${R(i.t)}</h3><p>${R(i.d)}</p></div>`)}<p style="margin-top:26px">${btn(b.cta)}</p></div></section>`;
    case 'texto': return `<section><div class="w" style="max-width:780px">${head(`<p class="mut">${R(b.text)}</p>`)}</div></section>`;
    case 'cta_final': return `<section class="alt"><div class="w center" style="max-width:760px">${head(b.text ? `<p class="mut">${R(b.text)}</p>` : '')}${btn(b.cta)}</div></section>`;
    case 'form': return `<section id="form"><div class="w center" style="max-width:640px">${head(b.text ? `<p class="mut">${R(b.text)}</p>` : '')}<form id="f" novalidate><input name="name" placeholder="Seu nome" required autocomplete="name"><input name="phone" placeholder="WhatsApp com DDD" required autocomplete="tel" inputmode="tel"><input name="email" type="email" placeholder="E-mail (opcional)" autocomplete="email"><input class="hp" name="website" tabindex="-1" autocomplete="off"><label class="lg"><input type="checkbox" name="consent" required> <span>Concordo em receber contato sobre ${E(l.product.nome || l.name)}${l.privacyUrl ? `. <a href="${E(l.privacyUrl)}" target="_blank" rel="noopener">Política de privacidade</a>` : ''}.</span></label><button class="btn" type="submit">${E(b.cta || 'Enviar')}</button><div id="ok">Recebemos seus dados. Entraremos em contato.</div></form>${l.whatsapp ? `<a class="wa" href="https://wa.me/${E(l.whatsapp)}?text=${encodeURIComponent('Olá! Vim pela página: ' + (l.name || ''))}" target="_blank" rel="noopener">Prefere falar no WhatsApp?</a>` : ''}</div></section>`;
  } return '';
}
async function lpHTML(l, p, opts) {
  opts = opts || {}; const T0 = l.theme || {}, hx = (v, d) => /^#[0-9a-f]{6}$/i.test(String(v)) ? v : d, fn = (v, d) => (String(v || '').replace(/[^\w \-]/g, '').trim().slice(0, 60) || d);
  const th = {accent: hx(T0.accent, '#e4572e'), bg: hx(T0.bg, '#ffffff'), fg: hx(T0.fg, '#141414'), dark: !!T0.dark, head: fn(T0.head, 'Poppins'), body: fn(T0.body, 'Inter')};
  const TR = {metaPixel: /^\d{5,20}$/.test(l.tracking && l.tracking.metaPixel || '') ? l.tracking.metaPixel : '', ga4: /^G-[A-Z0-9]{4,14}$/.test(l.tracking && l.tracking.ga4 || '') ? l.tracking.ga4 : ''};
  const blocks = (l.blocks || []).filter(b => b.on), hero = blocks.find(b => b.t === 'hero'), leadsUrl = state.workspace.leadsUrl || '';
  const sections = []; let hasForm = false, countdown = '';
  if (l.type === 'evento' && /^\d{4}-\d{2}-\d{2}/.test(l.product.data || '')) countdown = `<div class="cd" id="cd" data-t="${lpE(l.product.data)}"><div><b id="cdd">0</b><small>dias</small></div><div><b id="cdh">0</b><small>horas</small></div><div><b id="cdm">0</b><small>min</small></div></div>`;
  for (const b of blocks) { const img = b.imgId ? await lpImg(b.imgId) : ''; if (b.t === 'form') hasForm = true; sections.push(lpBlockHTML(l, b, {img, countdown: b.t === 'hero' ? countdown : ''})); }
  const title = (hero && hero.title ? hero.title.replace(/\*\*/g, '') : l.name) + (l.product.nome ? ' · ' + l.product.nome : ''), desc = (hero && hero.text || l.sub || '').replace(/\*\*/g, '').slice(0, 160), cta = hero ? lpCta(l, hero) : null;
  const track = opts.preview ? '' : [TR.metaPixel ? `<script>!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,'script','https://connect.facebook.net/en_US/fbevents.js');fbq('init','${TR.metaPixel}');fbq('track','PageView');</script>` : '', TR.ga4 ? `<script async src="https://www.googletagmanager.com/gtag/js?id=${TR.ga4}"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','${TR.ga4}');</script>` : ''].join('');
  const js = `<script>(function(){var f=document.getElementById('f');if(f)f.addEventListener('submit',function(e){e.preventDefault();var d={source:${JSON.stringify(l.name || 'landing').replace(/</g, '\\u003c')}};new FormData(f).forEach(function(v,k){d[k]=v});if(d.website)return;if(!d.name||!d.phone||!d.consent){alert('Preencha nome, WhatsApp e aceite o contato.');return}delete d.consent;d.consent='sim';var q=location.search.slice(1).split('&');q.forEach(function(x){var s=x.split('=');if(s[0].indexOf('utm_')===0)d[s[0]]=decodeURIComponent(s[1]||'')});${opts.preview ? "document.getElementById('ok').style.display='block';return;" : `var url=${JSON.stringify(leadsUrl).replace(/</g, '\\u003c')};if(!url){alert('Formulário sem destino configurado.');return}`}fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)}).then(function(r){if(!r.ok)throw 0;f.querySelectorAll('input,button').forEach(function(x){x.disabled=true});document.getElementById('ok').style.display='block';if(window.fbq)fbq('track','Lead');if(window.gtag)gtag('event','generate_lead')}).catch(function(){alert('Não foi possível enviar. Tente pelo WhatsApp.')})});var c=document.getElementById('cd');if(c){var t=new Date(c.dataset.t).getTime();var u=function(){var s=Math.max(0,Math.floor((t-Date.now())/1000));document.getElementById('cdd').textContent=Math.floor(s/86400);document.getElementById('cdh').textContent=Math.floor(s%86400/3600);document.getElementById('cdm').textContent=Math.floor(s%3600/60)};u();setInterval(u,30000)}${opts.preview ? "document.querySelectorAll('a[href^=\"http\"]').forEach(function(a){a.addEventListener('click',function(e){e.preventDefault()})});" : ''}})();</script>`;
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${lpE(title)}</title><meta name="description" content="${lpE(desc)}"><meta property="og:title" content="${lpE(title)}"><meta property="og:description" content="${lpE(desc)}"><meta name="theme-color" content="${th.accent}">${lpFontsLink(th)}<style>${lpCss(th)}</style>${track}</head><body>${sections.join('\n')}<footer><div class="w">${lpE(p.name)} · ${new Date().getFullYear()}${l.privacyUrl ? ` · <a href="${lpE(l.privacyUrl)}" style="color:inherit">Privacidade</a>` : ''}</div></footer>${cta && hero ? `<div class="bar"><a class="btn" href="${lpE(cta.href)}"${cta.ext ? ' target="_blank" rel="noopener"' : ''}>${lpE(hero.cta || LP_TYPE_INFO[l.type || 'generico'].cta)}</a></div>` : ''}${js}</body></html>`;
}
