/* ===== Mesa de edição · exportar e importar =====
   Exporta HTML (arquivo único), CSS, ZIP (páginas + css + imagens), JSON do Studio e Elementor (contêineres e widgets do Elementor GRÁTIS).
   Importa Elementor (template .json, kit .zip, contêiner e seção antiga), HTML (por estilos calculados, sem rodar scripts) e JSON do Studio. */
const mzDl = (name, data, type) => download(name, data, type);
async function mzImgBytes(imgId) { try { const b = await imgGet(imgId); if (!b) return null; return {bytes: new Uint8Array(await b.arrayBuffer()), type: b.type || 'image/png'}; } catch (e) { return null; } }
const mzExt = t => ({'image/png': 'png', 'image/jpeg': 'jpg', 'image/webp': 'webp', 'image/gif': 'gif', 'image/svg+xml': 'svg'})[t] || 'png';
function mzImgIds(m, pages) { const ids = new Set(); const sc = n => mzWalk(n, x => { [x.props.imgId, x.props.poster].concat(x.props.imgs || []).forEach(i => i && ids.add(i)); ['d', 't', 'm'].forEach(b => { String(x.style[b].backgroundImage || '').replace(/mzimg:([\w-]+)/g, (a, id) => { ids.add(id); return a; }); }); }); pages.forEach(p => sc(p.root)); m.comps.forEach(c => sc(c.root)); return [...ids]; }
const mzSlug = s => String(s || 'pagina').toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'pagina';

function mzModalExport() {
  const m = mzM(), pg = mzPg(); mzModal('Exportar', `<p class="mz-hint" style="margin-top:0">Escolha o que exportar. A principal saída é o Elementor (versão grátis, sem Pro): contêineres e widgets nativos, com o resto do visual em um CSS extra.</p>
    <label class="mz-ck"><input type="radio" name="mzxs" value="page" checked> Só a página atual (<b>${esc(pg.name)}</b>)</label><label class="mz-ck"><input type="radio" name="mzxs" value="all"> Todas as páginas (${m.pages.length})</label>
    <div class="mz-xgrid"><button class="mz-tpl" onclick="mzDoExport('elementor')"><b>Elementor (.json)</b><small>Modelo para Modelos → Importar. Estrutura, estilos, responsivo e links.</small></button><button class="mz-tpl" onclick="mzDoExport('html')"><b>HTML</b><small>Arquivo único, com CSS e imagens dentro.</small></button><button class="mz-tpl" onclick="mzDoExport('css')"><b>CSS</b><small>O CSS da página (variáveis do Design System incluídas).</small></button><button class="mz-tpl" onclick="mzDoExport('zip')"><b>ZIP do site</b><small>HTML, CSS e pasta de imagens, pronto para hospedar.</small></button><button class="mz-tpl" onclick="mzDoExport('json')"><b>JSON do Studio</b><small>O site inteiro, para outro projeto ou backup.</small></button></div><div id="mzXmsg" class="mz-hint"></div>`, {wide: true});
}
async function mzDoExport(fmt) {
  const m = mzM(), scope = (document.querySelector('input[name=mzxs]:checked') || {}).value || 'page', pages = scope === 'all' ? m.pages : [mzPg()], msg = t => { const e = document.getElementById('mzXmsg'); if (e) e.textContent = t; }; msg('Gerando…'); await mzLoadImgs();
  try {
    if (fmt === 'json') { mzDl(mzSlug(MZ.p.name) + '-site.mesa.json', JSON.stringify({mesaStudio: 1, name: MZ.p.name, mesa: {ds: m.ds, pages: scope === 'all' ? m.pages : pages, comps: m.comps}}, null, 1), 'application/json'); msg('JSON baixado.'); return; }
    if (fmt === 'html') { for (const pg of pages) { const html = await mzInlineImgDoc(m, pg); mzDl(mzSlug(pg.slug || pg.name) + '.html', html, 'text/html'); } msg(pages.length + ' arquivo(s) HTML baixado(s).'); return; }
    if (fmt === 'css') { const ctx = {mode: 'out', comps: m.comps, img: () => ''}; for (const pg of pages) mzDl(mzSlug(pg.slug || pg.name) + '.css', mzTreeCss(pg.root, m.ds, ctx), 'text/css'); msg('CSS baixado. As imagens de fundo apontam para um endereço vazio: use o ZIP para levar as imagens.'); return; }
    if (fmt === 'zip') {
      const ids = mzImgIds(m, pages), map = {}, files = [], enc = new TextEncoder(); let k = 1; for (const id of ids) { const b = await mzImgBytes(id); if (b) { const nm = `assets/img-${k++}.${mzExt(b.type)}`; map[id] = nm; files.push({name: nm, data: b.bytes}); } }
      pages.forEach(pg => { const base = pg.home ? 'index' : mzSlug(pg.slug || pg.name), cssFile = `css/${base}.css`, ctxCss = {mode: 'out', comps: m.comps, img: id => map[id] ? '../' + map[id] : ''}; files.push({name: base + '.html', data: enc.encode(mzDoc(m, pg, {img: id => map[id] || '', cssFile}))}); files.push({name: cssFile, data: enc.encode(mzTreeCss(pg.root, m.ds, ctxCss))}); });
      files.push({name: 'LEIA-ME.txt', data: enc.encode(`Site exportado pela Mesa de páginas do Ampliação Studio.\nProjeto: ${MZ.p.name}\nPáginas: ${pages.map(p => p.name).join(', ')}\nAbra index.html. Os formulários precisam de um endereço de recebimento (leads) configurado em cada formulário.\n`)}); mzDl(mzSlug(MZ.p.name) + '-site.zip', makeZip(files), 'application/zip'); msg('ZIP baixado.'); return;
    }
    if (fmt === 'elementor') {
      const ctx = {mode: 'out', comps: m.comps, img: () => ''}; let css = ''; const ids = mzImgIds(m, pages), map = {}; for (const id of ids) map[id] = await mzBlobData(id);
      for (const pg of pages) { const json = mzElementor(pg, m, map); mzDl(mzSlug(pg.slug || pg.name) + '.elementor.json', JSON.stringify(json), 'application/json'); const c = mzNodeCss(pg.root, Object.assign({}, ctx, {img: id => map[id] || ''})); css += `/* ${pg.name} */\n` + c.d + (c.t ? `@media (max-width:1024px){${c.t}}` : '') + (c.m ? `@media (max-width:767px){${c.m}}` : '') + '\n'; }
      mzDl('mesa-css-extra.css', mzDsCss(m.ds) + MZ_BASE_CSS.replace(/body\{[^}]*\}/, '') + css, 'text/css'); msg('Elementor baixado. Importe em Elementor → Modelos → Importar. O visual completo vem em mesa-css-extra.css: cole em Aparência → Personalizar → CSS adicional.'); return;
    }
  } catch (e) { msg('Erro: ' + e.message); }
}
/* ---------- Elementor ---------- */
const mzEid = () => Math.random().toString(16).slice(2, 9);
function mzEl4(v) { v = String(v == null ? '' : v).trim(); const m = /^(-?[\d.]+)(px|%|em|rem|vh|vw)?$/.exec(v); return m ? {unit: m[2] || 'px', size: +m[1], sizes: []} : null; }
function mzEDim(v) { const parts = String(v == null ? '' : v).trim().split(/\s+/); if (!parts[0]) return null; const px = x => { const m = /^(-?[\d.]+)(px)?$/.exec(x); return m ? String(+m[1]) : '0'; }; const p = parts.map(px); const [t, r, b, l] = p.length === 1 ? [p[0], p[0], p[0], p[0]] : p.length === 2 ? [p[0], p[1], p[0], p[1]] : p.length === 3 ? [p[0], p[1], p[2], p[1]] : p; return {unit: 'px', top: t, right: r, bottom: b, left: l, isLinked: false}; }
function mzResolveVar(v, ds) { return String(v || '').replace(/var\(--mz-c-(\w+)\)/g, (m, k) => { if (ds.colors[k]) return ds.colors[k]; const x = /^x(\d+)$/.exec(k); return x && ds.extra[+x[1] - 1] ? ds.extra[+x[1] - 1].value : '#000000'; }).replace(/var\(--mz-r-(\w+)\)/g, (m, k) => (ds.radius[k] || 0) + 'px').replace(/var\(--mz-sp-(\w+)\)/g, (m, k) => (ds.space[k] || 0) + 'px'); }
function mzElSettings(n, ds, imgMap) {
  const s = {}, put = (bp, k, v) => { if (v != null && v !== '') s[k + (bp === 'd' ? '' : bp === 't' ? '_tablet' : '_mobile')] = v; }; const sfx = {d: '', t: '_tablet', m: '_mobile'};
  ['d', 't', 'm'].forEach(bp => { const st = n.style[bp]; if (!st) return; const R = k => mzResolveVar(st[k], ds);
    if (st.flexDirection) put(bp, 'flex_direction', st.flexDirection); if (st.justifyContent) put(bp, 'flex_justify_content', st.justifyContent); if (st.alignItems) put(bp, 'flex_align_items', st.alignItems); if (st.flexWrap) put(bp, 'flex_wrap', st.flexWrap);
    if (st.gap != null) { const g = mzEl4(st.gap); if (g) put(bp, 'flex_gap', {unit: g.unit, size: g.size, column: String(g.size), row: String(g.size), isLinked: true}); }
    if (st.padding) put(bp, 'padding', mzEDim(st.padding)); else if (st.paddingTop || st.paddingRight || st.paddingBottom || st.paddingLeft) put(bp, 'padding', mzEDim([st.paddingTop || 0, st.paddingRight || 0, st.paddingBottom || 0, st.paddingLeft || 0].join(' '))); if (st.margin) put(bp, 'margin', mzEDim(st.margin));
    if (st.backgroundColor) { s.background_background = 'classic'; put(bp, 'background_color', R('backgroundColor')); } if (st.width) { const w = mzEl4(st.width); if (w) put(bp, 'width', w); } if (st.minHeight) { const w = mzEl4(st.minHeight); if (w) put(bp, 'min_height', w); }
    if (st.borderRadius) { const r = mzEDim(R('borderRadius')); if (r) put(bp, 'border_radius', r); } if (st.textAlign) put(bp, 'align', st.textAlign);
  });
  if (n.cls || true) s._css_classes = [mzCls(n), n.cls].filter(Boolean).join(' '); if (n.htmlId) s._element_id = n.htmlId; return s;
}
function mzElementorNode(n, ds, imgMap, comps) {
  if (n.hidden) return null; const base = {id: mzEid(), settings: {}, elements: []}; let kids = () => (n.children || []).map(c => mzElementorNode(c, ds, imgMap, comps)).filter(Boolean);
  const S = mzElSettings(n, ds, imgMap), st = n.style.d, col = k => mzResolveVar(st[k], ds), fs = bp => mzEl4(n.style[bp] && n.style[bp].fontSize), P = n.props;
  const typo = o => { const t = mzTypoOf(n); if (n.style.d.fontSize) { const f = mzEl4(n.style.d.fontSize); if (f) { o.typography_typography = 'custom'; o.typography_font_size = f; } } else if (t && ds.type[t]) { o.typography_typography = 'custom'; o.typography_font_size = {unit: 'px', size: ds.type[t].size, sizes: []}; o.typography_font_weight = String(ds.type[t].weight); } if (n.style.d.fontWeight) { o.typography_typography = 'custom'; o.typography_font_weight = String(n.style.d.fontWeight); } ['t', 'm'].forEach(bp => { const f = fs(bp); if (f) o['typography_font_size' + (bp === 't' ? '_tablet' : '_mobile')] = f; }); return o; };
  const html = h => ({id: mzEid(), elType: 'widget', widgetType: 'html', settings: Object.assign({html: h}, {_css_classes: S._css_classes}), elements: []});
  const w = (type, set) => ({id: mzEid(), elType: 'widget', widgetType: type, settings: Object.assign({}, set, {_css_classes: S._css_classes, _element_id: S._element_id}), elements: []});
  switch (n.type) {
    case 'page': return kids();
    case 'section': case 'container': case 'column': case 'div': case 'form': case 'link': { const set = Object.assign({}, S, {content_width: (n.props.boxed ? 'boxed' : 'full')}); if (n.props.boxed && n.props.w) set.boxed_width = {unit: 'px', size: n.props.w, sizes: []}; if (st.display === 'grid') { set.container_type = 'grid'; const m = /repeat\((\d+)/.exec(st.gridTemplateColumns || ''); if (m) set.grid_columns_grid = {unit: 'fr', size: +m[1], sizes: []}; } else if (!set.flex_direction) set.flex_direction = 'column'; if (n.type === 'form') return Object.assign(base, {elType: 'container', settings: set, isInner: false, elements: [w('shortcode', {shortcode: '[amp_lead_form title="" button="Enviar"]'})]}); return Object.assign(base, {elType: 'container', settings: set, isInner: false, elements: kids()}); }
    case 'heading': return w('heading', typo({title: P.text.replace(/\n/g, '<br>'), header_size: 'h' + (P.level || 2), align: st.textAlign || '', title_color: col('color') || ds.colors.text}));
    case 'text': return w('text-editor', typo({editor: P.html, text_color: col('color') || ''}));
    case 'image': case 'logo': { const u = P.imgId ? (imgMap[P.imgId] || '') : P.src; const o = {image: {url: u, id: ''}, image_size: 'full', align: st.textAlign || ''}; if (P.href) o.link = {url: P.href, is_external: '', nofollow: ''}; if (st.width) { const wd = mzEl4(st.width); if (wd) o.width = wd; } return w('image', o); }
    case 'video': { const v = mzVideoEmbed(P.url); if (v && v.iframe) return w('video', {video_type: /youtube/.test(v.iframe) ? 'youtube' : 'vimeo', [/youtube/.test(v.iframe) ? 'youtube_url' : 'vimeo_url']: P.url}); return html(`<video src="${mzEsc(P.url)}" controls style="width:100%"></video>`); }
    case 'button': return w('button', typo({text: P.text, link: {url: P.href || '#', is_external: P.newTab ? 'on' : '', nofollow: ''}, align: st.textAlign || '', button_text_color: P.variant === 'solid' ? '#ffffff' : ds.colors.primary, background_color: P.variant === 'solid' ? ds.colors.primary : '', border_radius: {unit: 'px', top: String(ds.radius.md), right: String(ds.radius.md), bottom: String(ds.radius.md), left: String(ds.radius.md), isLinked: true}}));
    case 'divider': return w('divider', {style: 'solid', weight: {unit: 'px', size: ds.border.width, sizes: []}, color: ds.border.color});
    case 'spacer': { const h = mzEl4(st.height) || {unit: 'px', size: 32, sizes: []}; return w('spacer', {space: h}); }
    case 'list': return w('icon-list', {icon_list: P.items.map(t => ({text: t, selected_icon: {value: 'fas fa-check', library: 'fa-solid'}, _id: mzEid()}))});
    case 'accordion': return w('accordion', {tabs: P.items.map(i => ({tab_title: i.q, tab_content: i.a, _id: mzEid()}))});
    case 'badge': return w('heading', {title: P.text, header_size: 'span', typography_typography: 'custom', title_color: '#ffffff', _css_classes: S._css_classes + ' mz-badge'});
    case 'component': { const c = comps.find(x => x.id === P.ref); return c ? mzElementorNode(c.root, ds, imgMap, comps) : null; }
    default: { const ctx = {mode: 'out', comps, img: id => imgMap[id] || ''}; return html(mzNodeHtml(Object.assign({}, n, {hidden: false}), ctx)); }
  }
}
function mzElementor(pg, m, imgMap) { const arr = mzElementorNode(pg.root, m.ds, imgMap, m.comps) || []; const content = (Array.isArray(arr) ? arr : [arr]).map(e => Array.isArray(e) ? e : e).flat(); return {version: '0.4', title: pg.name, type: 'page', content, page_settings: {}, metadata: {mesa: 1}}; }

/* ---------- importar ---------- */
function mzModalImport() {
  mzModal('Importar', `<p class="mz-hint" style="margin-top:0">Traga um layout pronto. O que entra vira páginas editáveis do site; nada existente é apagado.</p>
    <div class="mz-xgrid"><button class="mz-tpl" onclick="mzImportPick('.json,.zip','elementor')"><b>Elementor</b><small>Modelo (.json) ou kit (.zip): contêineres e seções antigas.</small></button><button class="mz-tpl" onclick="mzImportPick('.html,.htm','html')"><b>HTML</b><small>Preserva o visual pelos estilos calculados, sem rodar scripts.</small></button><button class="mz-tpl" onclick="mzImportPick('.json','studio')"><b>JSON do Studio</b><small>Site exportado desta mesa.</small></button></div><div id="mzImsg" class="mz-hint"></div>`, {wide: true});
}
function mzImportPick(accept, kind) { const i = document.createElement('input'); i.type = 'file'; i.accept = accept; i.onchange = async () => { const f = i.files[0]; if (!f) return; if (f.size > 20e6) { document.getElementById('mzImsg').textContent = 'Arquivo grande demais (máx. 20 MB).'; return; } try { const n = await mzImportFile(f, kind); document.getElementById('mzImsg').textContent = n + ' página(s) importada(s).'; mzPageSelUpdate(); mzTouch(); } catch (e) { document.getElementById('mzImsg').textContent = 'Não consegui importar: ' + e.message; } }; i.click(); }
async function mzImportFile(file, kind) {
  const m = mzM(), buf = await file.arrayBuffer(), ext = (file.name.split('.').pop() || '').toLowerCase(); let pages = [];
  if (ext === 'zip') { const files = await docUnzip(buf, n => /\.json$/.test(n) && !/manifest|site-settings|global/.test(n)); for (const n of Object.keys(files)) { try { pages = pages.concat(mzFromElementor(JSON.parse(new TextDecoder().decode(files[n])), n.split('/').pop().replace(/\.json$/, ''))); } catch (e) { /* ignora arquivo */ } } }
  else if (ext === 'html' || ext === 'htm') pages = [await mzFromHtml(new TextDecoder().decode(buf), file.name.replace(/\.[^.]+$/, ''))];
  else { const j = JSON.parse(new TextDecoder().decode(buf)); if (j.mesaStudio || (j.mesa && j.mesa.pages)) { const r = normalizeMesa(j.mesa); r.pages.forEach(p => { pages.push(p); }); r.comps.forEach(c => { if (!m.comps.some(x => x.id === c.id) && m.comps.length < MZ_LIMITS.comps) m.comps.push(c); }); } else pages = mzFromElementor(j, file.name.replace(/\.[^.]+$/, '')); }
  pages = pages.filter(Boolean).slice(0, 20); if (!pages.length) throw new Error('não encontrei páginas neste arquivo.');
  pages.forEach(pg => { if (m.pages.length >= MZ_LIMITS.pages) return; const c = mzNormPage(pg); c.id = mzId(); c.home = false; c.slug = mzUniqueSlug(c.slug || mzSlug(c.name)); m.pages.push(c); }); persist(); return pages.length;
}
/* Elementor → nós */
const mzEnum = v => (v && typeof v === 'object') ? v : null;
function mzFromElementor(j, fallbackName) {
  const list = Array.isArray(j) ? j : (j.content || j.elements || []); const out = []; if (j && j.type && !/page|section|container/.test(j.type) && j.content === undefined && !Array.isArray(j)) return [];
  const root = mzNode('page', {}, {display: 'flex', flexDirection: 'column'}); let count = 0;
  const dim = (d, k) => { d = mzEnum(d); return d ? ((+d.top || 0) + 'px ' + (+d.right || 0) + 'px ' + (+d.bottom || 0) + 'px ' + (+d.left || 0) + 'px') : null; };
  const size = s => { s = mzEnum(s); return s && s.size !== '' && s.size != null ? s.size + (s.unit || 'px') : null; };
  const apply = (n, st) => { ['d', 't', 'm'].forEach(bp => { const x = bp === 'd' ? '' : bp === 't' ? '_tablet' : '_mobile'; const S = n.style[bp]; if (st['flex_direction' + x]) S.flexDirection = st['flex_direction' + x]; if (st['flex_justify_content' + x]) S.justifyContent = st['flex_justify_content' + x]; if (st['flex_align_items' + x]) S.alignItems = st['flex_align_items' + x]; const g = mzEnum(st['flex_gap' + x]) || mzEnum(st['gap' + x]); if (g && (g.size !== '' || g.column)) S.gap = (g.size || g.column || 0) + (g.unit || 'px'); const p = dim(st['padding' + x]); if (p) S.padding = p; const mg = dim(st['margin' + x]); if (mg) S.margin = mg; if (st['background_color' + x] && /^#|^rgb/.test(st['background_color' + x])) S.backgroundColor = st['background_color' + x]; const w = size(st['width' + x]); if (w) S.width = w; const mh = size(st['min_height' + x]); if (mh) S.minHeight = mh; const br = dim(st['border_radius' + x]); if (br) S.borderRadius = String(+st['border_radius' + x].top || 0) + 'px'; if (st['align' + x]) S.textAlign = st['align' + x]; if (bp === 'd' && st.title_color) S.color = st.title_color; if (st['typography_font_size' + x]) { const f = size(st['typography_font_size' + x]); if (f) S.fontSize = f; } if (bp === 'd' && st.typography_font_weight) S.fontWeight = st.typography_font_weight; }); if (st._css_classes) n.cls = String(st._css_classes).replace(/[^\w\- ]/g, '').slice(0, 100); if (st._element_id && /^[A-Za-z][\w-]*$/.test(st._element_id)) n.htmlId = st._element_id; };
  const conv = (e, depth) => {
    if (!e || ++count > MZ_LIMITS.nodes || depth > 12) return null; const st = e.settings || {};
    if (e.elType === 'container') { const n = mzNode(depth === 0 ? 'section' : 'container', {boxed: st.content_width !== 'full'}); n.style.d.display = st.container_type === 'grid' ? 'grid' : 'flex'; if (!st.flex_direction && st.container_type !== 'grid') n.style.d.flexDirection = 'column'; if (st.container_type === 'grid' && mzEnum(st.grid_columns_grid)) n.style.d.gridTemplateColumns = `repeat(${+st.grid_columns_grid.size || 2},1fr)`; if (st.boxed_width && n.props.boxed) n.props.w = +mzEnum(st.boxed_width).size || 0; apply(n, st); n.children = (e.elements || []).map(c => conv(c, depth + 1)).filter(Boolean); return n; }
    if (e.elType === 'section') { const n = mzNode('section', {boxed: st.layout !== 'full_width'}); n.style.d.display = 'block'; apply(n, st); const row = mzNode('container', {}, {display: 'flex', flexDirection: 'row', gap: 24}); row.style.t.flexDirection = 'column'; (e.elements || []).forEach(c => { const x = conv(c, depth + 1); if (x) row.children.push(x); }); n.children = [row]; return n; }
    if (e.elType === 'column') { const n = mzNode('column', {}, {display: 'flex', flexDirection: 'column', gap: 12}); const w = st._column_size; if (w) n.style.d.flex = `1 1 ${+w}%`; apply(n, st); n.children = (e.elements || []).map(c => conv(c, depth + 1)).filter(Boolean); return n; }
    if (e.elType !== 'widget') return null; const t = e.widgetType; let n;
    if (t === 'heading') { n = mzNode('heading', {text: String(st.title || '').replace(/<br\s*\/?>/g, '\n').replace(/<[^>]+>/g, ''), level: +((/\d/.exec(st.header_size || 'h2') || [2])[0]) || 2}); }
    else if (t === 'text-editor') n = mzNode('text', {html: mzRich(st.editor || '')});
    else if (t === 'image') { const u = mzEnum(st.image) && st.image.url; n = mzNode('image', {src: MZ_URL(u), alt: ''}); if (mzEnum(st.link) && st.link.url) n.props.href = MZ_URL(st.link.url); }
    else if (t === 'button') n = mzNode('button', {text: st.text || 'Botão', href: MZ_URL(mzEnum(st.link) && st.link.url) || '#'});
    else if (t === 'divider') n = mzNode('divider', {}); else if (t === 'spacer') { n = mzNode('spacer', {}); const h = size(st.space); if (h) n.style.d.height = h; }
    else if (t === 'icon-list') n = mzNode('list', {items: (st.icon_list || []).map(i => i.text).filter(Boolean), icon: 'check-circle'});
    else if (t === 'accordion' || t === 'toggle') n = mzNode('accordion', {items: (st.tabs || []).map(i => ({q: i.tab_title, a: mzRich(i.tab_content || '')}))});
    else if (t === 'tabs') n = mzNode('tabs', {items: (st.tabs || []).map(i => ({t: i.tab_title, c: mzRich(i.tab_content || '')}))});
    else if (t === 'video') n = mzNode('video', {url: MZ_URL(st.youtube_url || st.vimeo_url || st.hosted_url && st.hosted_url.url)});
    else if (t === 'html') n = mzNode('text', {html: mzRich(String(st.html || '').replace(/<(script|style)[\s\S]*?<\/\1>/gi, ''))});
    else if (t === 'shortcode') n = mzNode('form', {source: 'elementor'}, null, [mzNode('input', {kind: 'text', name: 'name', label: 'Nome', required: true}), mzNode('input', {kind: 'tel', name: 'phone', label: 'WhatsApp', required: true}), mzNode('button', {text: 'Enviar', href: '#'})]);
    else if (t === 'icon') n = mzNode('icon', {name: 'star', size: 40}); else if (t === 'counter') n = mzNode('heading', {text: String(st.ending_number || 0), level: 2});
    else if (t === 'google_maps') n = mzNode('text', {html: '<p>[Mapa: ' + mzEsc(st.address || '') + ']</p>'});
    else if (t === 'image-box') { n = mzNode('container', {}, {display: 'flex', flexDirection: 'column', gap: 12}, [mzNode('image', {src: MZ_URL(mzEnum(st.image) && st.image.url)}), mzNode('heading', {text: st.title_text || '', level: 3}), mzNode('text', {html: mzRich(st.description_text || '')})]); }
    else if (t === 'icon-box') { n = mzNode('container', {}, {display: 'flex', flexDirection: 'column', gap: 8}, [mzNode('icon', {name: 'star', size: 36}), mzNode('heading', {text: st.title_text || '', level: 3}), mzNode('text', {html: mzRich(st.description_text || '')})]); }
    else n = mzNode('text', {html: mzRich('<p>[Widget “' + mzEsc(t || '?') + '” do Elementor não tem equivalente aqui. Reconstrua com os elementos da mesa.]</p>')});
    apply(n, st); return n;
  };
  list.forEach(e => { const n = conv(e, 0); if (n) { if (n.type === 'section' || n.type === 'container') { n.type = 'section'; root.children.push(n); } else root.children.push(MZB.sec([n], {minHeight: 40})); } }); if (!root.children.length) return [];
  return [{id: mzId(), name: j.title || fallbackName || 'Importada', slug: mzSlug(j.title || fallbackName), root}];
}
/* HTML → nós, por estilos calculados (iframe isolado, sem scripts) */
async function mzFromHtml(html, name) {
  const doc = new DOMParser().parseFromString(html, 'text/html'); doc.querySelectorAll('script,noscript,iframe,object,embed,link[rel=preload],meta[http-equiv]').forEach(n => n.remove()); doc.querySelectorAll('*').forEach(el => Array.from(el.attributes).forEach(a => { if (/^on/i.test(a.name) || /^\s*javascript:/i.test(a.value)) el.removeAttribute(a.name); }));
  const css = Array.from(doc.querySelectorAll('style')).map(s => s.textContent).join('\n'), body = doc.body ? doc.body.innerHTML : '', title = (doc.title || name || 'Importada');
  const ifr = document.createElement('iframe'); ifr.setAttribute('sandbox', 'allow-same-origin'); ifr.style.cssText = 'position:fixed;left:-9999px;top:0;width:1280px;height:900px;visibility:hidden'; document.body.appendChild(ifr);
  await new Promise(r => { ifr.onload = r; ifr.srcdoc = `<!doctype html><html><head><meta charset="utf-8"><style>${css.replace(/<\/style/gi, '')}</style></head><body>${body}</body></html>`; }); await new Promise(r => setTimeout(r, 120));
  const idoc = ifr.contentDocument, win = ifr.contentWindow; let count = 0; const px = v => { const n = parseFloat(v); return isNaN(n) ? null : Math.round(n * 10) / 10; }; const rgb = c => { const m = /rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*([\d.]+))?\)/.exec(c || ''); if (!m || (m[4] != null && +m[4] === 0)) return ''; return '#' + [m[1], m[2], m[3]].map(x => (+x).toString(16).padStart(2, '0')).join(''); };
  const styleOf = (el, tag) => { const c = win.getComputedStyle(el), s = {}, set = (k, v) => { if (v != null && v !== '') s[k] = v; }; const bg = rgb(c.backgroundColor); if (bg) set('backgroundColor', bg); const thb = /mz-theme\.invalid\/([\w-]+)/.exec(c.backgroundImage || ''); if (thb) { set('backgroundImage', `url(mzimg:${thb[1]})`); set('backgroundSize', c.backgroundSize === 'contain' ? 'contain' : 'cover'); set('backgroundPosition', 'center'); set('backgroundRepeat', 'no-repeat'); } if (c.backgroundImage && c.backgroundImage !== 'none' && /gradient/.test(c.backgroundImage)) set('backgroundImage', c.backgroundImage); const col = rgb(c.color); if (col && ['H1', 'H2', 'H3', 'H4', 'H5', 'H6', 'P', 'A', 'SPAN', 'LI', 'BUTTON', 'DIV'].includes(tag)) set('color', col);
    const pads = [c.paddingTop, c.paddingRight, c.paddingBottom, c.paddingLeft].map(px); if (pads.some(v => v)) set('padding', pads.map(v => (v || 0) + 'px').join(' ')); const mar = [c.marginTop, c.marginRight, c.marginBottom, c.marginLeft].map(px); if (mar.some(v => v) && !mar.some(v => v < 0)) set('margin', mar.map(v => (v || 0) + 'px').join(' '));
    if (c.display.includes('flex')) { set('display', 'flex'); set('flexDirection', c.flexDirection); set('flexWrap', c.flexWrap); set('justifyContent', c.justifyContent === 'normal' ? '' : c.justifyContent); set('alignItems', c.alignItems === 'normal' ? '' : c.alignItems); const g = px(c.columnGap) || px(c.gap); if (g) set('gap', g + 'px'); } else if (c.display.includes('grid')) { set('display', 'grid'); const cols = c.gridTemplateColumns.split(' ').filter(Boolean).length; if (cols > 1) set('gridTemplateColumns', `repeat(${cols},1fr)`); const g = px(c.columnGap); if (g) set('gap', g + 'px'); }
    set('textAlign', ['center', 'right', 'justify'].includes(c.textAlign) ? c.textAlign : ''); if (/^(H[1-6]|P|A|SPAN|LI|BUTTON)$/.test(tag)) { set('fontSize', (px(c.fontSize) || 16) + 'px'); set('fontWeight', c.fontWeight); set('lineHeight', c.lineHeight !== 'normal' ? String(Math.round(parseFloat(c.lineHeight) / parseFloat(c.fontSize) * 100) / 100) : ''); set('letterSpacing', c.letterSpacing !== 'normal' ? c.letterSpacing : ''); if (c.textTransform !== 'none') set('textTransform', c.textTransform); }
    const br = px(c.borderTopLeftRadius); if (br) set('borderRadius', br + 'px'); const bw = px(c.borderTopWidth); if (bw && c.borderTopStyle !== 'none') { set('borderWidth', bw + 'px'); set('borderStyle', c.borderTopStyle); set('borderColor', rgb(c.borderTopColor) || '#cccccc'); } const mw = px(c.maxWidth); if (mw && c.maxWidth !== 'none') set('maxWidth', mw + 'px'); if (c.boxShadow && c.boxShadow !== 'none') set('boxShadow', c.boxShadow.replace(/rgba?\([^)]*\)/g, m => m)); return mzNormStyle(s); };
  const conv = (el, depth) => {
    if (++count > 800 || depth > 12 || el.nodeType !== 1) return null; const tag = el.tagName, c = win.getComputedStyle(el); if (c.display === 'none' || ['STYLE', 'SCRIPT', 'HEAD', 'META', 'LINK', 'TITLE', 'BR'].includes(tag)) return null; const lt = tag.toLowerCase(); let n;
    if (/^H[1-6]$/.test(tag)) n = mzNode('heading', {text: el.innerText.trim().slice(0, 600), level: +tag[1]});
    else if (tag === 'P' || tag === 'BLOCKQUOTE') n = mzNode('text', {html: mzRich(el.innerHTML)});
    else if (tag === 'IMG') { const src = el.getAttribute('src') || '', th = /mz-theme\.invalid\/([\w-]+)/.exec(src); n = mzNode('image', th ? {imgId: th[1], alt: el.getAttribute('alt') || ''} : {src: MZ_URL(src), alt: el.getAttribute('alt') || ''}); }
    else if (tag === 'A' && !el.children.length || tag === 'BUTTON') { n = mzNode('button', {text: el.innerText.trim().slice(0, 100) || 'Botão', href: MZ_URL(el.getAttribute('href') || '')}); n.props.variant = rgb(c.backgroundColor) ? 'solid' : 'outline'; }
    else if (tag === 'UL' || tag === 'OL') { const items = Array.from(el.children).filter(x => x.tagName === 'LI').map(x => x.innerText.trim()).filter(Boolean); if (!items.length) return null; n = mzNode('list', {items: items.slice(0, 30), ordered: tag === 'OL'}); }
    else if (tag === 'HR') n = mzNode('divider', {}); else if (tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT') n = mzNode('input', {kind: tag === 'TEXTAREA' ? 'textarea' : (['email', 'tel', 'number'].includes(el.type) ? el.type : 'text'), name: (el.name || 'campo').replace(/[^\w-]/g, ''), placeholder: el.placeholder || ''});
    else if (tag === 'SVG') { n = mzNode('svg', {svg: mzSafeSvg(el.outerHTML)}); }
    else if (tag === 'TABLE') { n = mzNode('table', {rows: Array.from(el.rows).slice(0, 30).map(r => Array.from(r.cells).map(x => x.innerText.trim()))}); }
    else if (tag === 'VIDEO' || tag === 'IFRAME') return null;
    else { const kids = Array.from(el.childNodes); const onlyText = kids.length && kids.every(k => k.nodeType === 3 || (k.nodeType === 1 && ['SPAN', 'B', 'STRONG', 'I', 'EM', 'A', 'BR', 'SMALL', 'U'].includes(k.tagName))) && el.innerText.trim(); if (onlyText && !el.querySelector('div,section,ul,ol,img,h1,h2,h3')) n = mzNode('text', {html: mzRich(el.innerHTML)}); else { n = mzNode(depth === 0 || lt === 'section' || lt === 'header' || lt === 'footer' || lt === 'main' ? (depth <= 1 ? 'section' : 'container') : 'container', depth <= 1 && (lt === 'section' || lt === 'header' || lt === 'footer') ? {boxed: false, tag: lt === 'section' ? 'section' : lt} : {}); n.children = kids.map(k => k.nodeType === 1 ? conv(k, depth + 1) : (k.nodeType === 3 && k.textContent.trim().length > 1 ? mzNode('text', {html: mzRich(k.textContent.trim())}) : null)).filter(Boolean); if (!n.children.length) return null; } }
    n.style.d = Object.assign(styleOf(el, tag), n.style.d); if (el.id && /^[A-Za-z][\w-]*$/.test(el.id)) n.htmlId = el.id; return n;
  };
  const root = mzNode('page', {}, {display: 'flex', flexDirection: 'column'}); let tops = Array.from(idoc.body.children).filter(x => !/^(SCRIPT|STYLE|LINK|NOSCRIPT)$/.test(x.tagName)); for (let u = 0; u < 3; u++) { if (tops.length === 1 && /^(DIV|MAIN|ARTICLE|FORM)$/.test(tops[0].tagName) && tops[0].children.length >= 2 && !rgb(win.getComputedStyle(tops[0]).backgroundColor)) tops = Array.from(tops[0].children).filter(x => !/^(SCRIPT|STYLE|LINK|NOSCRIPT)$/.test(x.tagName)); else break; } tops.forEach(e => { const n = conv(e, 0); if (!n) return; if (n.type === 'section') root.children.push(n); else { const s = MZB.sec([n], {minHeight: 40}); root.children.push(s); } }); ifr.remove();
  if (!root.children.length) throw new Error('o HTML não tem conteúdo visível.'); return {id: mzId(), name: title.slice(0, 60), slug: mzSlug(title), root};
}
