/* ===== Sites (várias páginas) com a lógica StoryBrand: BrandScript → páginas geradas, cabeçalho/menu/rodapé compartilhados, exportação em ZIP.
   Os modelos abaixo seguem o roteiro público do StoryBrand (personagem, problema, guia, plano, chamada para ação, falha, sucesso); montados a partir do
   método, não de uma leitura de site específico. ===== */
const SITE_TPL = {
  storybrand: {label: 'StoryBrand · página única', why: 'O wireframe clássico do StoryBrand numa página só: promessa → problema e consequências → proposta de valor → guia (empatia e autoridade) → plano em 3 passos → chamada para ação → sucesso → isca (lead magnet) → perguntas.',
    pages: [{slug: 'index', label: 'Início', role: 'home', blocks: ['hero', 'dor', 'beneficios', 'autoridade', 'prova', 'passos', 'cta_final', 'texto', 'form', 'faq']}]},
  servicos: {label: 'StoryBrand · site de serviços', why: 'Empresa ou profissional que presta serviço: Início (StoryBrand), Serviços, Sobre e Contato.',
    pages: [{slug: 'index', label: 'Início', role: 'home', blocks: ['hero', 'dor', 'beneficios', 'passos', 'prova', 'cta_final']}, {slug: 'servicos', label: 'Serviços', role: 'oferta', blocks: ['hero', 'solucao', 'beneficios', 'passos', 'faq', 'cta_final']}, {slug: 'sobre', label: 'Sobre', role: 'sobre', blocks: ['hero', 'autoridade', 'texto', 'prova', 'cta_final']}, {slug: 'contato', label: 'Contato', role: 'contato', blocks: ['hero', 'form', 'local']}]},
  produtos: {label: 'StoryBrand · site de produtos', why: 'Marca com produtos: Início (StoryBrand), Produtos, Sobre e Contato.',
    pages: [{slug: 'index', label: 'Início', role: 'home', blocks: ['hero', 'dor', 'beneficios', 'prova', 'passos', 'cta_final']}, {slug: 'produtos', label: 'Produtos', role: 'oferta', blocks: ['hero', 'conteudo', 'beneficios', 'oferta', 'faq']}, {slug: 'sobre', label: 'Sobre', role: 'sobre', blocks: ['hero', 'autoridade', 'texto', 'prova']}, {slug: 'contato', label: 'Contato', role: 'contato', blocks: ['hero', 'form', 'local']}]},
  autoridade: {label: 'StoryBrand · mentoria / autoridade', why: 'Especialista que vende método, mentoria ou consultoria: Início, Método, Sobre e Contato.',
    pages: [{slug: 'index', label: 'Início', role: 'home', blocks: ['hero', 'dor', 'beneficios', 'autoridade', 'prova', 'cta_final']}, {slug: 'metodo', label: 'Método', role: 'oferta', blocks: ['hero', 'solucao', 'passos', 'para_quem', 'prova', 'faq']}, {slug: 'sobre', label: 'Sobre', role: 'sobre', blocks: ['hero', 'autoridade', 'texto', 'prova']}, {slug: 'contato', label: 'Contato', role: 'contato', blocks: ['hero', 'form', 'local']}]}
};
const SITE_ROLE = {home: 'Página inicial, no formato do StoryBrand: abre com a promessa e o botão; mostra o problema e o custo de não agir; a proposta de valor; o guia; o plano; a chamada final.', oferta: 'Página que detalha o que é oferecido e como funciona.', sobre: 'Página sobre quem está por trás: empatia (entende o problema do cliente) e autoridade (credenciais reais), sem falar só de si.', contato: 'Página de contato: facilitar o primeiro passo, com formulário curto.'};
const BS_FIELDS = [
  ['Personagem (o cliente)', [['who', 'Quem é o cliente?', 'Ex.: autônomo que usa consignado para fechar o mês'], ['wants', 'O que ele quer? (uma coisa só)', 'Ex.: pagar menos juros e dormir tranquilo']]],
  ['Problema', [['external', 'Problema externo (o que acontece)', ''], ['internal', 'Problema interno (como ele se sente)', ''], ['philosophical', 'Problema filosófico (por que é errado alguém passar por isso)', '']]],
  ['Guia', [['empathy', 'Empatia (mostre que entende)', ''], ['authority', 'Autoridade (credenciais REAIS: casos, tempo, números, prêmios)', 'Só o que existe de verdade']]],
  ['Plano', [['step1', 'Passo 1', ''], ['step2', 'Passo 2', ''], ['step3', 'Passo 3', ''], ['agreement', 'Plano de acordo (garantias, compromissos)', '']]],
  ['Chamada para ação', [['direct', 'Chamada direta (comprar, agendar, ligar)', 'Ex.: Agende uma conversa'], ['transitional', 'Chamada transitória / isca (e-book, checklist, vídeo)', 'Ex.: Baixe o checklist grátis']]],
  ['Falha e sucesso', [['failure', 'O que ele evita? (falha / custo de não agir)', ''], ['success', 'Como fica a vida dele depois? (sucesso)', ''], ['identity', 'Quem ele se torna? (transformação de identidade)', '']]]
];
const siteCur = () => { const p = curProject(); return p && p.sites.find(x => x.id === lpUI.site); };
const siteA = esc;

/* ---------- lista ---------- */
function lpMainSites(b, p) {
  if (lpUI.site && siteCur()) return siteEditor(b, p, siteCur());
  b.innerHTML = `<div class="panel"><div class="section-row"><div><h3>Sites</h3><p class="muted" style="margin:2px 0 0;font-size:12.5px">Vários páginas com o mesmo cabeçalho, menu e rodapé, escritas a partir do BrandScript do StoryBrand. Escolha um modelo, preencha (ou peça para a IA preencher) o BrandScript e gere as páginas; cada página abre no editor visual.</p></div><div class="row-gap" style="flex-wrap:wrap"><button class="btn sm" onclick="tplImportOpen()" title="Traz seções de templates HTML (Envato etc.) para o banco">📥 Importar template</button><button class="btn sm" onclick="tplBankOpen()">🗂 Banco de templates</button><button class="btn dark sm" onclick="siteNewModal()">＋ Novo site</button></div></div>
  ${p.sites.length ? p.sites.map(s => { const pg = p.landings.filter(l => l.siteId === s.id); return `<div class="list-item"><div><strong>${siteA(s.name)}</strong><small>${siteA((SITE_TPL[s.tpl] || {label: 'Site'}).label)} · ${pg.length} página(s): ${siteA(pg.map(l => l.navLabel || l.name).join(', '))}</small></div><div class="row-gap"><button class="btn sm dark" onclick="lpUI.site='${s.id}';renderLandings()">Abrir</button><button class="btn sm" onclick="siteExport('${s.id}')">⬇ ZIP</button><button class="btn sm" onclick="siteDel('${s.id}')">×</button></div></div>`; }).join('') : '<p class="muted" style="margin-top:10px">Nenhum site ainda.</p>'}</div>`;
}
function siteNewModal() {
  const p = curProject();
  showModal('Novo site', `<div class="field"><label>Nome do site</label><input id="snName" placeholder="Ex.: Studio Aurora"></div><div class="field"><label>Produto ou serviço principal (opcional)</label><select id="snP"><option value="">— nenhum —</option>${p.products.map(x => `<option value="${x.id}">${siteA(x.name)}</option>`).join('')}</select></div><div class="okr-label">MODELO</div><div class="lp-types">${Object.entries(SITE_TPL).map(([k, t], i) => `<label class="lp-type"><input type="radio" name="snT" value="${k}" ${i === 1 ? 'checked' : ''}><b>${siteA(t.label)}</b><small class="muted">${siteA(t.why)}</small><small class="mono muted">${t.pages.map(x => x.label).join(' · ')}</small></label>`).join('')}</div><div class="modal-actions"><button class="btn" onclick="closeModal()">Cancelar</button><button class="btn dark" onclick="siteCreate()">Criar site</button></div>`);
  document.getElementById('modalBox').classList.add('wide');
}
function siteCreate() {
  const p = curProject(), name = $('snName').value.trim() || 'Meu site', tpl = (document.querySelector('input[name=snT]:checked') || {}).value || 'servicos', T = SITE_TPL[tpl], pr = p.products.find(x => x.id === $('snP').value);
  const site = normalizeSites([{id: uid('st'), name, tpl, productId: pr ? pr.id : '', brand: name, headerCta: 'Fale com a gente', brief: pr ? [pr.summary && 'Descrição: ' + pr.summary].filter(Boolean).join('\n') : ''}])[0];
  p.sites.push(site); const theme = lpTheme(p);
  T.pages.forEach(pg => { const l = normalizeLandings([{id: uid('lp'), name: name + ' — ' + pg.label, siteId: site.id, slug: pg.slug, navLabel: pg.label, type: 'generico', productId: pr ? pr.id : '', product: pr ? {nome: pr.name, preco: pr.price, publico: pr.audience, checkout: pr.checkout} : {}, theme, cta: 'Fale com a gente', blocks: pg.blocks.map(lpBlockNew), status: 'Rascunho'}])[0]; l.siteRole = pg.role; p.landings.push(l); });
  persist(); closeModal(); lpUI.main = 'sites'; lpUI.site = site.id; renderLandings();
}
function siteDel(id) { if (!confirm('Excluir o site e todas as suas páginas?')) return; const p = curProject(); p.sites = p.sites.filter(s => s.id !== id); p.landings = p.landings.filter(l => l.siteId !== id); lpUI.site = ''; persist(); renderLandings(); }

/* ---------- editor do site ---------- */
function siteEditor(b, p, s) {
  const pages = p.landings.filter(l => l.siteId === s.id), prods = p.products;
  b.innerHTML = `<div class="row-gap" style="margin-bottom:10px"><button class="btn sm" onclick="lpUI.site='';renderLandings()">← Todos os sites</button><h2 style="margin:0">${siteA(s.name)}</h2><span class="so-badge" style="margin:0">${siteA((SITE_TPL[s.tpl] || {}).label || '')}</span><span style="flex:1"></span><button class="btn dark" onclick="siteExport('${s.id}')">⬇ Exportar site (ZIP)</button></div>
  <div class="lp-wrap" style="grid-template-columns:minmax(0,1fr) 420px"><div>
  ${accSec('st', 'bs', '1 · BrandScript (StoryBrand)', 'a história que o site conta', `<div class="row-gap" style="margin-bottom:8px;flex-wrap:wrap"><button class="btn sm dark" onclick="siteFillBS()" ${aiReady() && !lpUI.busy ? '' : 'disabled'}>${lpUI.busy === 'bs' ? 'Pensando…' : '✦ Preencher com IA a partir do resumo'}</button></div><div class="field"><label>Resumo do negócio (o que vende, para quem, diferenciais reais)</label><textarea rows="5" oninput="siteCur().brief=this.value;persist()" placeholder="Cole aqui o que você sabe: produto, público, dores, números reais, garantias…">${siteA(s.brief)}</textarea></div>${BS_FIELDS.map(([t, fs]) => `<div class="okr-label" style="margin-top:10px">${t.toUpperCase()}</div>${fs.map(([k, l, ph]) => `<div class="field"><label>${l}</label><textarea rows="2" oninput="siteCur().bs.${k}=this.value;persist()" placeholder="${siteA(ph)}">${siteA(s.bs[k])}</textarea></div>`).join('')}`).join('')}`, true)}
  ${accSec('st', 'pg', '2 · Páginas do site', pages.length + ' páginas', `<small class="muted block" style="margin-bottom:6px">Cada página abre no editor (blocos, editor visual, estilo). O menu segue esta ordem.</small>${pages.map((l, i) => `<div class="list-item"><div><strong>${siteA(l.navLabel || l.name)}</strong><small>/${siteA(l.slug === 'index' ? '' : l.slug + '.html')} · ${(l.blocks || []).filter(x => x.on).length} blocos${lpPending(l) ? ` · <span class="so-warn">${lpPending(l)} a confirmar</span>` : ''}${l.vis ? ' · editor visual' : ''}</small></div><div class="row-gap"><button class="btn sm" onclick="siteMovePage('${l.id}',-1)" ${i === 0 ? 'disabled' : ''}>▲</button><button class="btn sm" onclick="siteMovePage('${l.id}',1)" ${i === pages.length - 1 ? 'disabled' : ''}>▼</button><button class="btn sm dark" onclick="lpUI.back='site';lpOpen('${l.id}')">Abrir</button><button class="btn sm" onclick="siteGenOne('${l.id}')" ${aiReady() && !lpUI.busy ? '' : 'disabled'} title="Reescreve esta página com o BrandScript">✦</button><button class="btn sm" onclick="sitePageDel('${l.id}')">×</button></div></div>`).join('')}<div class="row-gap" style="margin-top:8px"><button class="btn dark" onclick="siteGenAll()" ${aiReady() && !lpUI.busy ? '' : 'disabled'}>${lpUI.busy === 'all' ? 'Escrevendo as páginas…' : '✦ Gerar todas as páginas com o BrandScript'}</button><button class="btn" onclick="siteAddPage()">＋ Página</button></div><small class="muted block" style="margin-top:6px">A IA escreve só com o BrandScript e os fatos do produto. O que faltar fica como <b>[CONFIRMAR]</b>.</small>`, true)}</div>
  <div>${accSec('st', 'ch', 'Cabeçalho, menu e rodapé', '', `<div class="field"><label>Nome da marca (no cabeçalho)</label><input value="${siteA(s.brand)}" oninput="siteCur().brand=this.value;persist()"></div><div class="field"><label>Botão do cabeçalho (vazio = sem botão)</label><input value="${siteA(s.headerCta)}" oninput="siteCur().headerCta=this.value;persist()"></div><div class="field"><label>Texto do rodapé</label><textarea rows="2" oninput="siteCur().footer=this.value;persist()">${siteA(s.footer)}</textarea></div><div class="okr-label" style="margin-top:8px">COMPARTILHAMENTO E FAVICON</div><div class="field"><label>Descrição do site (aparece no Google e ao compartilhar o link)</label><textarea rows="2" oninput="siteCur().desc=this.value;persist()" placeholder="Uma ou duas frases sobre o que o site oferece">${siteA(s.desc)}</textarea></div><div class="field"><label>Endereço do site publicado (https://…)</label><input value="${siteA(s.baseUrl)}" onchange="siteCur().baseUrl=seoBase(this.value);persist();renderLandings()" placeholder="https://www.seudominio.com.br"></div><div class="row-gap" style="flex-wrap:wrap;margin-bottom:8px"><button class="btn sm" onclick="siteImg('ogImgId')">📚 Imagem de compartilhamento (${s.ogImgId ? '✓' : 'não definida'})</button>${s.ogImgId ? `<button class="btn sm" onclick="siteImg('ogImgId',1)">×</button>` : ''}<button class="btn sm" onclick="siteImg('faviconImgId')">📚 Favicon (${s.faviconImgId ? '✓' : 'não definido'})</button>${s.faviconImgId ? `<button class="btn sm" onclick="siteImg('faviconImgId',1)">×</button>` : ''}</div><small class="muted block" style="margin-bottom:8px">Imagem 1200×630 funciona melhor (cortada ao centro). Favicon: imagem quadrada. Cada página pode ter título, descrição e imagem próprios na aba Publicar.</small><div class="field"><label>Contato no rodapé (endereço, telefone, e-mail)</label><textarea rows="3" oninput="siteCur().contact=this.value;persist()">${siteA(s.contact)}</textarea></div>${p.products.length ? `<div class="field"><label>Produto principal</label><select onchange="siteSetProduct(this.value)"><option value="">— nenhum —</option>${p.products.map(x => `<option value="${x.id}" ${x.id === s.productId ? 'selected' : ''}>${siteA(x.name)}</option>`).join('')}</select></div>` : ''}`, true)}
  <div class="panel" style="margin-top:10px"><h3>Publicar</h3><p class="muted" style="font-size:12.5px;margin:0">O ZIP traz uma página por arquivo (<span class="mono">index.html</span>, <span class="mono">servicos.html</span>…), com o menu ligando uma à outra e funcionando no celular. Suba tudo na raiz da hospedagem. O formulário usa a URL de leads de Configurações.</p></div>${typeof wpPanel === 'function' ? wpPanel(s, p) : ''}</div></div>`;
}
function siteImg(k, clear) { if (clear) { siteCur()[k] = ''; persist(); renderLandings(); return; } libPick(r => { siteCur()[k] = r.id; persist(); renderLandings(); }); }
function siteSetProduct(id) { const p = curProject(), s = siteCur(); s.productId = id; const x = p.products.find(y => y.id === id); p.landings.filter(l => l.siteId === s.id).forEach(l => { l.productId = id; if (x) Object.assign(l.product, {nome: x.name, preco: x.price, publico: x.audience, checkout: x.checkout}); }); persist(); renderLandings(); }
function siteMovePage(id, d) { const p = curProject(), a = p.landings, i = a.findIndex(l => l.id === id), s = a[i].siteId; let j = i + d; while (j >= 0 && j < a.length && a[j].siteId !== s) j += d; if (j < 0 || j >= a.length) return; [a[i], a[j]] = [a[j], a[i]]; persist(); renderLandings(); }
function sitePageDel(id) { if (!confirm('Remover esta página do site?')) return; const p = curProject(); p.landings = p.landings.filter(l => l.id !== id); persist(); renderLandings(); }
function siteAddPage() {
  showModal('Nova página do site', `<div class="field"><label>Nome no menu</label><input id="spN" placeholder="Ex.: Blog, Depoimentos"></div><div class="field"><label>Estrutura</label><select id="spT"><option value="home">Início (StoryBrand)</option><option value="oferta">Serviços / produtos</option><option value="sobre">Sobre</option><option value="contato">Contato</option></select></div><div class="modal-actions"><button class="btn" onclick="closeModal()">Cancelar</button><button class="btn dark" onclick="siteAddPageSave()">Criar</button></div>`);
}
function siteAddPageSave() {
  const p = curProject(), s = siteCur(), n = $('spN').value.trim() || 'Nova página', role = $('spT').value, pg = Object.values(SITE_TPL).flatMap(t => t.pages).find(x => x.role === role), base = slug(n) || 'pagina', ex = p.landings.filter(l => l.siteId === s.id).map(l => l.slug);
  let sl = base; for (let i = 2; ex.includes(sl); i++) sl = base + '-' + i;
  const l = normalizeLandings([{id: uid('lp'), name: s.name + ' — ' + n, siteId: s.id, slug: sl.slice(0, 40), navLabel: n, type: 'generico', productId: s.productId, theme: ((p.landings.find(x => x.siteId === s.id) || {}).theme) || lpTheme(p), blocks: pg.blocks.map(lpBlockNew)}])[0]; l.siteRole = role; p.landings.push(l); persist(); closeModal(); renderLandings();
}
/* ---------- IA: BrandScript e páginas ---------- */
async function siteFillBS() {
  const s = siteCur(); if (!s.brief.trim()) { toast('Escreva o resumo do negócio primeiro.'); return; } lpUI.busy = 'bs'; renderLandings();
  try {
    const x = curProject().products.find(y => y.id === s.productId), facts = x ? `PRODUTO: ${x.name}. Benefícios: ${x.benefits.join(' | ')}. Características: ${x.features.join(' | ')}. Provas reais: ${x.proofs.join(' | ') || '(nenhuma)'}.\n` : '';
    const j = await aiJSON('Você é consultor de marca pelo método StoryBrand. Monte o BrandScript do negócio com base SÓ no resumo (e nos fatos do produto). Frases curtas, na voz do cliente. NUNCA invente credenciais, números, prêmios, garantias ou clientes: onde faltar, escreva "[CONFIRMAR: o que falta]". JSON: {"who":"","wants":"","external":"","internal":"","philosophical":"","empathy":"","authority":"","step1":"","step2":"","step3":"","agreement":"","direct":"","transitional":"","failure":"","success":"","identity":""}', facts + s.brief);
    Object.keys(s.bs).forEach(k => { if (j[k] != null && !s.bs[k].trim()) s.bs[k] = String(j[k]).slice(0, 800); }); persist(); toast('BrandScript preenchido (só os campos vazios). Revise e ajuste.');
  } catch (e) { toast(eErr(e)); }
  lpUI.busy = ''; renderLandings();
}
const SB_ROLE = {hero: 'promessa do que a pessoa conquista (título aspiracional, subtítulo com para quem/como) + botão direto', dor: 'problema externo, interno e filosófico + o custo de não agir (falha)', beneficios: 'proposta de valor: 3 benefícios do sucesso', autoridade: 'o guia: empatia (entendo você) + autoridade (credenciais REAIS)', prova: 'depoimentos/casos REAIS (senão [CONFIRMAR])', passos: 'o plano em 3 passos simples + plano de acordo', cta_final: 'chamada direta para ação, lembrando o que ele evita e conquista', texto: 'o sucesso: como a vida do cliente fica depois + quem ele se torna', form: 'chamada transitória (isca) ou contato: o que ele recebe ao enviar', faq: 'objeções que travam a decisão', solucao: 'como o serviço resolve, passo a passo', local: 'onde estamos / como falar com a gente', conteudo: 'o que está incluso em cada produto/serviço', oferta: 'o que está incluso, condição e botão', para_quem: 'para quem é e para quem não é'};
function siteBSText(s) { const b = s.bs, L = [['Cliente', b.who], ['Quer', b.wants], ['Problema externo', b.external], ['Problema interno', b.internal], ['Problema filosófico', b.philosophical], ['Empatia', b.empathy], ['Autoridade', b.authority], ['Plano', [b.step1, b.step2, b.step3].filter(Boolean).join(' → ')], ['Plano de acordo', b.agreement], ['Chamada direta', b.direct], ['Chamada transitória (isca)', b.transitional], ['Falha (custo de não agir)', b.failure], ['Sucesso', b.success], ['Identidade', b.identity]]; return L.filter(x => x[1]).map(x => `${x[0]}: ${x[1]}`).join('\n'); }
async function siteGenPage(s, l) {
  const blocks = l.blocks.filter(b => b.on), role = SITE_ROLE[l.siteRole] || '';
  const j = await motJSON('Você escreve sites pelo método StoryBrand: o cliente é o herói, a marca é o guia. Português do Brasil, frases curtas e específicas, sem clichês. ' + (eBrandTxt() ? '\n' + eBrandTxt().slice(0, 4000) : ''),
    `PÁGINA: ${l.navLabel} — ${role}\n\nBRANDSCRIPT:\n${siteBSText(s) || '(vazio)'}\n\n${lpProductFacts(l)}RESUMO:\n${s.brief.slice(0, 5000)}\n\nESTRUTURA (na ordem; um objeto por bloco):\n${blocks.map((b, i) => `${i + 1}. t="${b.t}" — ${LP_BLOCK[b.t].ai}. Papel no StoryBrand: ${SB_ROLE[b.t] || ''}`).join('\n')}\n\nFormato: JSON {"blocks":[{"t":"hero","kicker":"","title":"","text":"","cta":"","note":"","name":"","price":"","items":[{"t":"","d":""}],"yes":[],"no":[]}]}. Regras: NUNCA invente números, depoimentos, nomes, prazos, garantias ou credenciais: onde faltar, [CONFIRMAR: o que falta]; sem promessa de resultado garantido.`, 6500);
  const got = Array.isArray(j.blocks) ? j.blocks : []; if (!got.length) throw new Error('a IA não devolveu a página ' + l.navLabel + '.'); lpMerge(l, got); if (l.vis) l.vis = bxFromBlocks(l);
}
async function siteGenAll() {
  const p = curProject(), s = siteCur(); if (!siteBSText(s)) { toast('Preencha o BrandScript (ou use “Preencher com IA”) antes de gerar.'); return; } lpUI.busy = 'all'; renderLandings();
  try { for (const l of p.landings.filter(x => x.siteId === s.id)) { await siteGenPage(s, l); persist(); } toast('Páginas escritas. Abra cada uma para revisar o que estiver em [CONFIRMAR].'); } catch (e) { toast(eErr(e)); }
  lpUI.busy = ''; renderLandings();
}
async function siteGenOne(id) { const p = curProject(), s = siteCur(), l = p.landings.find(x => x.id === id); if (!siteBSText(s)) { toast('Preencha o BrandScript antes.'); return; } lpUI.busy = 'one'; renderLandings(); try { await siteGenPage(s, l); persist(); toast('Página reescrita.'); } catch (e) { toast(eErr(e)); } lpUI.busy = ''; renderLandings(); }

/* ---------- exportação ---------- */
async function siteExport(id) {
  const p = curProject(), s = p.sites.find(x => x.id === id), pages = p.landings.filter(l => l.siteId === id); if (!pages.length) { toast('O site não tem páginas.'); return; }
  const pend = pages.reduce((n, l) => n + lpPending(l), 0); if (pend) toast(`Atenção: ${pend} item(ns) ainda como [CONFIRMAR].`); toast('Montando o ZIP…');
  const enc = new TextEncoder(), files = []; const imgSeen = new Set(); for (const l of pages) { const ex = lpExtractImgs(await lpHTML(l, p)); files.push({name: lpFile(l), data: enc.encode(ex.html)}); ex.files.forEach(f => { if (!imgSeen.has(f.name)) { imgSeen.add(f.name); files.push(f); } }); }
  const seen = new Set(); for (const l of pages) for (const a of await lpAssets(l, p)) if (!seen.has(a.name)) { seen.add(a.name); files.push(a); }
  { const tl = pages.find(l => (l.thanks || {}).mode === 'page' || !l.thanks); if (tl && pages.some(l => (l.thanks || {}).mode !== 'none' && (l.thanks || {}).mode !== 'url' && (l.blocks.some(b => b.t === 'form' && b.on) || (l.vis && JSON.stringify(l.vis).includes('"t":"form"'))))) files.push({name: 'obrigado.html', data: enc.encode(await lpThanksHTML(pages.find(l => (l.thanks || {}).mode === 'page') || tl, p))}); }
  if (!files.some(f => f.name === 'index.html')) files[0] = {name: 'index.html', data: files[0].data};
  download(slug(s.name) + '-site.zip', makeZip(files), 'application/zip'); pages.forEach(l => { l.status = 'Exportada'; }); persist();
}
