/* Redes sociais, mensageiros, vídeo, marketplaces e ferramentas. nome (Simple Icons, CC0): [rótulo, palavras-chave]
   'ph:<nome>' = Phosphor (MIT) quando o Simple Icons não tem. */
module.exports = {
  instagram: ['Instagram', 'rede social foto stories reels'], facebook: ['Facebook', 'rede social meta'], whatsapp: ['WhatsApp', 'mensagem contato atendimento zap'], youtube: ['YouTube', 'vídeo canal'], tiktok: ['TikTok', 'vídeo curto rede social'],
  x: ['X (antigo Twitter)', 'rede social twitter'], telegram: ['Telegram', 'mensagem grupo canal'], threads: ['Threads', 'rede social meta texto'], pinterest: ['Pinterest', 'inspiração imagens'], snapchat: ['Snapchat', 'rede social'],
  reddit: ['Reddit', 'fórum comunidade'], discord: ['Discord', 'comunidade chat'], twitch: ['Twitch', 'transmissão ao vivo live'], spotify: ['Spotify', 'música podcast'], bluesky: ['Bluesky', 'rede social'], mastodon: ['Mastodon', 'rede social'],
  github: ['GitHub', 'código programação'], behance: ['Behance', 'portfólio design'], dribbble: ['Dribbble', 'portfólio design'], medium: ['Medium', 'blog artigos'], signal: ['Signal', 'mensagem'], wechat: ['WeChat', 'mensagem'], line: ['LINE', 'mensagem'],
  messenger: ['Messenger', 'mensagem facebook'], zoom: ['Zoom', 'reunião videochamada'], notion: ['Notion', 'organização notas'], figma: ['Figma', 'design'], ifood: ['iFood', 'delivery comida pedido'], shopee: ['Shopee', 'marketplace loja'], pix: ['Pix', 'pagamento transferência'],
  paypal: ['PayPal', 'pagamento'], stripe: ['Stripe', 'pagamento'], mercadopago: ['Mercado Pago', 'pagamento'], googlemaps: ['Google Maps', 'mapa localização endereço'], gmail: ['Gmail', 'e-mail'], google: ['Google', 'busca'], googleplay: ['Google Play', 'aplicativo android loja'],
  vimeo: ['Vimeo', 'vídeo'], soundcloud: ['SoundCloud', 'áudio música'], substack: ['Substack', 'newsletter'], patreon: ['Patreon', 'apoio assinatura'], linktree: ['Linktree', 'link na bio'], tumblr: ['Tumblr', 'blog'], flickr: ['Flickr', 'fotos'], quora: ['Quora', 'perguntas'],
  applemusic: ['Apple Music', 'música'], youtubemusic: ['YouTube Music', 'música'], googlemeet: ['Google Meet', 'reunião videochamada'], applepodcasts: ['Apple Podcasts', 'podcast'], wordpress: ['WordPress', 'site blog'], shopify: ['Shopify', 'loja virtual e-commerce'],
  wix: ['Wix', 'site'], squarespace: ['Squarespace', 'site'], mailchimp: ['Mailchimp', 'e-mail marketing'], calendly: ['Calendly', 'agendamento'], trello: ['Trello', 'tarefas'], dropbox: ['Dropbox', 'arquivos nuvem'], googledrive: ['Google Drive', 'arquivos nuvem'],
  googleanalytics: ['Google Analytics', 'métricas'], googleads: ['Google Ads', 'anúncios'], meta: ['Meta', 'facebook instagram'], kick: ['Kick', 'transmissão ao vivo'], netflix: ['Netflix', 'filmes séries'], deezer: ['Deezer', 'música'], tidal: ['Tidal', 'música'],
  uber: ['Uber', 'transporte'], zapier: ['Zapier', 'automação'], airbnb: ['Airbnb', 'hospedagem'], tripadvisor: ['Tripadvisor', 'viagem avaliação'], yelp: ['Yelp', 'avaliações'], viber: ['Viber', 'mensagem'], imessage: ['iMessage', 'mensagem apple'],
  googlechat: ['Google Chat', 'mensagem'], clubhouse: ['Clubhouse', 'áudio'], bereal: ['BeReal', 'rede social'], onlyfans: ['OnlyFans', 'assinatura'], nubank: ['Nubank', 'banco cartão'], picpay: ['PicPay', 'pagamento'], pagseguro: ['PagSeguro', 'pagamento'],
  'ph:linkedin': ['LinkedIn', 'rede profissional carreira'], 'ph:slack': ['Slack', 'chat equipe'], 'ph:skype': ['Skype', 'videochamada'], 'ph:twitter': ['Twitter (pássaro)', 'rede social'], 'ph:google-chrome': ['Chrome', 'navegador'], 'ph:microsoft-teams': ['Microsoft Teams', 'reunião'],
  'ph:apple': ['Apple', 'maçã'], 'ph:amazon': ['Amazon', 'loja'], 'ph:android': ['Android', 'celular'], 'ph:app-store': ['App Store', 'aplicativo apple loja']
};
